(() => {
  const loading = document.getElementById('loading');
  function status(title, message, canRetry = false) {
    if (!loading) return;
    loading.classList.remove('hide');
    loading.innerHTML = `<div style="max-width:620px;padding:28px;text-align:center;color:#fff"><div class="loader" style="${canRetry ? 'display:none' : ''}"></div><h2 style="margin:0 0 10px">${title}</h2><p style="line-height:1.6;opacity:.9;word-break:break-word">${message}</p>${canRetry ? '<button onclick="location.reload()" style="border:0;border-radius:12px;padding:12px 18px;background:#d9b55d;color:#17362f;font-weight:800">Retry</button>' : ''}</div>`;
  }
  async function fromEsmSh(){const THREE=await import('https://esm.sh/three@0.164.1');const c=await import('https://esm.sh/three@0.164.1/examples/jsm/controls/OrbitControls.js');return{THREE,OrbitControls:c.OrbitControls,source:'esm.sh'}}
  async function fromJsDelivr(){const THREE=await import('https://cdn.jsdelivr.net/npm/three@0.164.1/+esm');const c=await import('https://cdn.jsdelivr.net/npm/three@0.164.1/examples/jsm/controls/OrbitControls.js/+esm');return{THREE,OrbitControls:c.OrbitControls,source:'jsDelivr'}}
  async function fromSkypack(){const THREE=await import('https://cdn.skypack.dev/three@0.164.1');const c=await import('https://cdn.skypack.dev/three@0.164.1/examples/jsm/controls/OrbitControls.js');return{THREE,OrbitControls:c.OrbitControls,source:'Skypack'}}
  async function loadEngine(){const attempts=[fromEsmSh,fromJsDelivr,fromSkypack],errors=[];for(let i=0;i<attempts.length;i++){status('Loading interactive 3D map…',`Connecting to 3D engine source ${i+1} of ${attempts.length}.`);try{const e=await Promise.race([attempts[i](),new Promise((_,r)=>setTimeout(()=>r(new Error('Connection timed out')),9000))]);if(!e.THREE||!e.OrbitControls)throw new Error('3D engine exports were incomplete');return e}catch(err){errors.push(err?.message||String(err))}}throw new Error(`All 3D engine sources failed: ${errors.join(' | ')}`)}

  const enhancedKaaba = String.raw`function kaaba(p,s=1,key='haram'){
    const g=new THREE.Group();g.position.copy(p);g.scale.setScalar(s);g.rotation.y=-0.055;
    const cloth=new THREE.MeshStandardMaterial({color:0x050505,roughness:.98,metalness:0});
    const cloth2=new THREE.MeshStandardMaterial({color:0x111111,roughness:.92,metalness:0});
    const gold=new THREE.MeshStandardMaterial({color:0xc99b32,roughness:.32,metalness:.68});
    const goldDark=new THREE.MeshStandardMaterial({color:0x8f6318,roughness:.43,metalness:.58});
    const silver=new THREE.MeshStandardMaterial({color:0xd8d8d3,roughness:.24,metalness:.88});
    const marble=new THREE.MeshStandardMaterial({color:0xe3ded3,roughness:.78,metalness:.02});
    const body=new THREE.Mesh(new THREE.BoxGeometry(5.52,6.58,4.74),cloth);body.position.y=3.29;body.castShadow=body.receiveShadow=true;g.add(body);
    const roof=new THREE.Mesh(new THREE.BoxGeometry(5.58,.13,4.80),cloth2);roof.position.y=6.64;roof.castShadow=true;g.add(roof);
    const skirtF=new THREE.Mesh(new THREE.BoxGeometry(5.70,.24,.25),marble);skirtF.position.set(0,.12,2.43);g.add(skirtF);const skirtB=skirtF.clone();skirtB.position.z=-2.43;g.add(skirtB);
    const skirtS=new THREE.Mesh(new THREE.BoxGeometry(.25,.24,4.72),marble);skirtS.position.set(2.83,.12,0);g.add(skirtS);const skirtS2=skirtS.clone();skirtS2.position.x=-2.83;g.add(skirtS2);
    const bf=new THREE.Mesh(new THREE.BoxGeometry(5.50,.72,.10),gold);bf.position.set(0,5.16,2.42);g.add(bf);const bb=bf.clone();bb.position.z=-2.42;g.add(bb);
    const bs=new THREE.Mesh(new THREE.BoxGeometry(.10,.72,4.70),gold);bs.position.set(2.79,5.16,0);g.add(bs);const bs2=bs.clone();bs2.position.x=-2.79;g.add(bs2);
    for(let i=-2.18;i<=2.18;i+=.54){const f=new THREE.Mesh(new THREE.BoxGeometry(.032,4.18,.024),cloth2);f.position.set(i,2.73,2.39);g.add(f);const b=f.clone();b.position.z=-2.39;g.add(b)}
    for(let z=-1.88;z<=1.88;z+=.54){const f=new THREE.Mesh(new THREE.BoxGeometry(.024,4.18,.032),cloth2);f.position.set(2.76,2.73,z);g.add(f);const b=f.clone();b.position.x=-2.76;g.add(b)}
    for(let i=-2.12;i<=2.12;i+=.70){const m=new THREE.Mesh(new THREE.BoxGeometry(.36,.11,.026),goldDark);m.position.set(i,5.16,2.49);g.add(m);const m2=m.clone();m2.position.z=-2.49;g.add(m2)}
    const frame=new THREE.Mesh(new THREE.BoxGeometry(1.62,2.60,.17),gold);frame.position.set(1.00,2.82,2.47);g.add(frame);
    const door=new THREE.Mesh(new THREE.BoxGeometry(1.38,2.34,.21),goldDark);door.position.set(1.00,2.82,2.54);g.add(door);
    for(let y=2.05;y<=3.58;y+=.51){const p1=new THREE.Mesh(new THREE.BoxGeometry(1.12,.052,.026),gold);p1.position.set(1.00,y,2.66);g.add(p1)}
    for(let x=.60;x<=1.40;x+=.40){const p1=new THREE.Mesh(new THREE.BoxGeometry(.052,1.92,.026),gold);p1.position.set(x,2.82,2.66);g.add(p1)}
    const sitara=new THREE.Mesh(new THREE.BoxGeometry(1.94,.50,.12),gold);sitara.position.set(1.00,4.29,2.50);g.add(sitara);
    const silverFrame=new THREE.Mesh(new THREE.TorusGeometry(.285,.080,14,38),silver);silverFrame.position.set(2.78,1.48,2.39);silverFrame.rotation.y=-Math.PI/4;g.add(silverFrame);
    const blackStone=new THREE.Mesh(new THREE.SphereGeometry(.205,22,16),new THREE.MeshStandardMaterial({color:0x010101,roughness:.70}));blackStone.position.set(2.82,1.48,2.44);blackStone.scale.set(.76,1,.30);g.add(blackStone);
    const mizab=new THREE.Mesh(new THREE.CylinderGeometry(.105,.105,1.30,18),gold);mizab.rotation.x=Math.PI/2;mizab.position.set(0,6.51,-2.93);g.add(mizab);
    const lip=new THREE.Mesh(new THREE.CylinderGeometry(.15,.11,.28,18),gold);lip.rotation.x=Math.PI/2;lip.position.set(0,6.51,-3.57);g.add(lip);
    const c1=new THREE.Mesh(new THREE.BoxGeometry(.10,6.35,.10),cloth2);c1.position.set(2.77,3.24,2.38);g.add(c1);const c2=c1.clone();c2.position.x=-2.77;g.add(c2);const c3=c1.clone();c3.position.z=-2.38;g.add(c3);const c4=c3.clone();c4.position.x=-2.77;g.add(c4);
    root.add(g);keyify(g,key);return g
  }`;

  const accurateProject = String.raw`function project(lat,lon){const scale=4.35,lat0=21.395,lon0=39.905;return new THREE.Vector3((lon-lon0)*111.32*Math.cos(lat0*Math.PI/180)*scale,0,(lat-lat0)*111.32*scale)}`;
  const accurateLabel = String.raw`function label(text,key,p){const c=document.createElement('canvas'),x=c.getContext('2d');c.width=560;c.height=112;x.fillStyle='rgba(5,47,40,.91)';x.roundRect(5,5,550,102,20);x.fill();x.strokeStyle='#d8b25a';x.lineWidth=4;x.stroke();x.fillStyle='white';x.font='700 27px Arial';x.textAlign='center';x.textBaseline='middle';x.fillText(text,280,56);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,depthTest:false}));s.position.copy(p).add(new THREE.Vector3(0,mode==='hajj'?3.5:2.2,0));s.scale.set(mode==='hajj'?7.2:5.2,mode==='hajj'?1.45:1.10,1);s.userData={key};root.add(s);labels.push(s);clickable.push(s)}`;
  const accurateMarker = String.raw`function marker(key,p,text){const g=new THREE.Group();g.position.copy(p);const size=mode==='hajj'?.62:.38;const ring=new THREE.Mesh(new THREE.TorusGeometry(size,.07,10,36),new THREE.MeshBasicMaterial({color:0xd8b25a}));ring.rotation.x=Math.PI/2;ring.position.y=.08;const orb=sph(size*.38,0xffdf83);orb.position.y=size*.95;orb.material.emissive=new THREE.Color(0x6c4c0e);orb.material.emissiveIntensity=.8;orb.userData={key};clickable.push(orb);g.add(ring,orb);root.add(g);label(text,key,p);pos[key]=p.clone()}`;
  const accurateTerrain = String.raw`function terrain(){const g=new THREE.Mesh(new THREE.PlaneGeometry(220,165,62,48),mat(0xb39a6d));g.rotation.x=-Math.PI/2;const a=g.geometry.attributes.position;for(let i=0;i<a.count;i++){const x=a.getX(i),y=a.getY(i),edgeX=Math.max(0,(Math.abs(x)-76)/25),edgeY=Math.max(0,(Math.abs(y)-52)/18);const ridge=(edgeX+edgeY)*7+Math.max(0,Math.sin(x*.075)+Math.cos(y*.09)-1.15)*2.3;a.setZ(ridge)}g.geometry.computeVertexNormals();g.receiveShadow=true;g.userData.terrain=true;root.add(g);for(let i=0;i<54;i++){const ang=Math.random()*Math.PI*2,r=72+Math.random()*30;const rock=new THREE.Mesh(new THREE.DodecahedronGeometry(1.2+Math.random()*2.1,0),mat(0x806b4d));rock.position.set(Math.cos(ang)*r,.55+Math.random()*1.1,Math.sin(ang)*r*.72);rock.scale.set(1.1+Math.random(),.45+.45*Math.random(),1.1+Math.random());rock.userData.terrain=true;root.add(rock)}}`;
  const accurateCity = String.raw`function city(p){const g=new THREE.Group();g.position.copy(p);const pad=cyl(6.7,6.7,.20,0xe8e2d5,64);pad.position.y=.10;g.add(pad);const local=new THREE.Group();g.add(local);root.add(g);const oldRoot=root;root=local;kaaba(new THREE.Vector3(0,.20,0),.42,'haram');root=oldRoot;for(let i=0;i<34;i++){const a=i/34*Math.PI*2,r=5.25+(i%3)*.32,b=box(.52,.95+(i%4)*.15,.52,0xe8e1d2);b.position.set(Math.cos(a)*r,b.geometry.parameters.height/2,Math.sin(a)*r);g.add(b)}for(let i=0;i<6;i++){const a=i/6*Math.PI*2,m=cyl(.10,.18,3.4,0xeee6d5,12);m.position.set(Math.cos(a)*6.0,1.7,Math.sin(a)*6.0);g.add(m)}const tower=box(1.8,8.4,1.8,0xb7ad9b);tower.position.set(-5.4,4.2,-5.6);g.add(tower);const clock=box(1.95,1.15,1.95,0x65806f);clock.position.set(-5.4,7.4,-5.6);g.add(clock);keyify(g,'haram')}`;
  const accurateTents = String.raw`function tents(p){const g=new THREE.Group();g.position.copy(p);g.rotation.y=-0.04;root.add(g);const valley=new THREE.Mesh(new THREE.CapsuleGeometry(6.2,14,8,24),mat(0xc8b487));valley.rotation.z=Math.PI/2;valley.scale.z=.72;valley.position.y=.06;g.add(valley);valley.userData.key='mina';clickable.push(valley);const tentGeo=new THREE.CylinderGeometry(0,.46,.82,10);const tentMat=mat(0xf5f1e7);const tents=new THREE.InstancedMesh(tentGeo,tentMat,126);tents.castShadow=tents.receiveShadow=true;const m=new THREE.Matrix4(),q=new THREE.Quaternion(),sc=new THREE.Vector3(1,1,1);let n=0;for(let x=-8.7;x<=8.7;x+=1.15){for(let z=-3.8;z<=3.8;z+=1.05){if(Math.abs(z)<.42||Math.abs(x)<.45)continue;m.compose(new THREE.Vector3(x,.42,z),q,sc);tents.setMatrixAt(n++,m)}}tents.count=n;g.add(tents);for(let z=-3.15;z<=3.15;z+=2.1){const road=box(18.5,.07,.28,0x77736b);road.position.set(0,.13,z);g.add(road)}const spine=box(.34,.07,8.4,0x77736b);spine.position.set(0,.14,0);g.add(spine);const mosque=box(4.1,.55,2.1,0xe8e2d7);mosque.position.set(1.8,.35,-5.0);g.add(mosque);for(let x=-1.45;x<=1.45;x+=.72){const dome=cyl(0,.30,.28,0xe8e2d7,18);dome.position.set(1.8+x,.76,-5.0);g.add(dome)}const min1=cyl(.08,.12,2.1,0xe8e2d7,10);min1.position.set(-.1,1.05,-5.0);g.add(min1);const min2=min1.clone();min2.position.x=3.7;g.add(min2);keyify(g,'mina')}`;
  const accurateArafah = String.raw`function arafah(p){const g=new THREE.Group();g.position.copy(p);root.add(g);const plain=new THREE.Mesh(new THREE.CircleGeometry(11.8,72),mat(0xcbb17b));plain.rotation.x=-Math.PI/2;plain.position.y=.05;g.add(plain);const boundary=new THREE.Mesh(new THREE.RingGeometry(10.9,11.25,72),new THREE.MeshBasicMaterial({color:0xe7c968,transparent:true,opacity:.75,side:THREE.DoubleSide}));boundary.rotation.x=-Math.PI/2;boundary.position.y=.09;g.add(boundary);const hill=cyl(1.15,4.4,4.25,0x8b7050,11);hill.position.set(3.1,2.12,-1.4);hill.scale.z=.72;g.add(hill);const cap=new THREE.Mesh(new THREE.DodecahedronGeometry(1.15,1),mat(0x84694b));cap.position.set(3.1,4.35,-1.4);cap.scale.set(1.8,.65,1.25);g.add(cap);const pillar=cyl(.12,.17,3.0,0xf6f4ed,12);pillar.position.set(3.1,6.0,-1.4);g.add(pillar);const mosque=box(7.7,.58,2.6,0xeae3d5);mosque.position.set(-5.0,.35,5.8);g.add(mosque);for(let i=0;i<10;i++){const d=cyl(0,.30,.30,0xeae3d5,18);d.position.set(-8.3+i*.74,.78,5.8);g.add(d)}const min1=cyl(.08,.13,2.45,0xeae3d5,10);min1.position.set(-8.7,1.22,5.8);g.add(min1);const min2=min1.clone();min2.position.x=-1.25;g.add(min2);keyify(g,'arafah')}`;
  const accurateMuz = String.raw`function muz(p){const g=new THREE.Group();g.position.copy(p);root.add(g);const base=new THREE.Mesh(new THREE.CircleGeometry(9.2,64),mat(0x8f7c5d));base.rotation.x=-Math.PI/2;base.position.y=.05;g.add(base);for(let i=0;i<18;i++){const pole=cyl(.045,.055,1.65,0x4f4f4f,8);pole.position.set((Math.random()-.5)*14,.83,(Math.random()-.5)*11);g.add(pole);const lamp=sph(.08,0xffd780);lamp.position.copy(pole.position).add(new THREE.Vector3(0,.84,0));lamp.material.emissive=new THREE.Color(0xffb84d);lamp.material.emissiveIntensity=1.1;g.add(lamp)}const mosque=box(5.2,.62,2.5,0xf0ede4);mosque.position.set(1.0,.36,-2.1);g.add(mosque);const dome=cyl(0,.78,.46,0xf0ede4,24);dome.position.set(1.0,.89,-2.1);g.add(dome);const m1=cyl(.07,.12,2.25,0xf0ede4,10);m1.position.set(-1.3,1.12,-2.1);g.add(m1);const m2=m1.clone();m2.position.x=3.3;g.add(m2);keyify(g,'muz')}`;
  const accurateJamarat = String.raw`function jamarat(p){const g=new THREE.Group();g.position.copy(p);g.rotation.y=.02;root.add(g);for(let l=0;l<4;l++){const deck=box(11.8,.30,3.4,0xb9bbb8);deck.position.y=.65+l*.92;g.add(deck)}for(let i=0;i<5;i++){const col=box(.38,4.15,.50,0xdadad5);col.position.set(-4.6+i*2.3,2.05,0);g.add(col)}const xs=[-3.65,-.55,3.1],zs=[0,0,0],lens=[1.75,2.0,2.45];xs.forEach((x,i)=>{const wall=box(.28,1.95,lens[i],0xeee9dd);wall.position.set(x,2.10,zs[i]);g.add(wall)});const ramp1=box(8.2,.24,1.35,0xb9bbb8);ramp1.rotation.z=-.13;ramp1.position.set(-8.0,1.06,-.88);g.add(ramp1);const ramp2=ramp1.clone();ramp2.rotation.z=.13;ramp2.position.set(8.0,1.06,.88);g.add(ramp2);keyify(g,'jamarat')}`;
  const accurateBuildHajj = String.raw`function buildHajj(){terrain();const ph=project(21.42250,39.82617),pm=project(21.41527,39.87780),pj=project(21.42139,39.87278),pa=project(21.35472,39.98389),pz=project(21.38930,39.91270);city(ph);tents(pm);arafah(pa);muz(pz);jamarat(pj);const route=[ph,project(21.418,39.850),pj,pm,project(21.393,39.930),pa,project(21.373,39.953),pz,pm,pj,ph].map(v=>v.clone().setY(.38));tube(route);[['haram',ph],['jamarat',pj],['mina',pm],['muz',pz],['arafah',pa]].forEach(([k,p])=>marker(k,p,DATA.hajj[k].n[lang==='en'?0:1]));Q('#scaleLabel').textContent='5 km'}`;

  const accurateBuildHaram = String.raw`function buildHaram(){const marble=new THREE.Mesh(new THREE.CircleGeometry(42,128),mat(0xf1efe9));marble.rotation.x=-Math.PI/2;marble.receiveShadow=true;root.add(marble);for(let r=7;r<=24;r+=3.4){const ring=new THREE.Mesh(new THREE.RingGeometry(r-.035,r+.035,128),new THREE.MeshBasicMaterial({color:0xcfc9bb,side:THREE.DoubleSide,transparent:true,opacity:.72}));ring.rotation.x=-Math.PI/2;ring.position.y=.05;root.add(ring)}kaaba(new THREE.Vector3(0,.05,0),1,'kaaba');
    const hit=new THREE.Mesh(new THREE.SphereGeometry(.38,16,12),new THREE.MeshBasicMaterial({transparent:true,opacity:.01,depthWrite:false}));hit.position.set(2.88,1.48,2.50);hit.userData.key='blackstone';root.add(hit);clickable.push(hit);
    const curve=new THREE.CatmullRomCurve3([new THREE.Vector3(-3.75,.38,-2.55),new THREE.Vector3(-4.55,.38,-3.75),new THREE.Vector3(-3.2,.38,-5.55),new THREE.Vector3(0,.38,-6.15),new THREE.Vector3(3.2,.38,-5.55),new THREE.Vector3(4.55,.38,-3.75),new THREE.Vector3(3.75,.38,-2.55)]);const hijr=new THREE.Mesh(new THREE.TubeGeometry(curve,72,.17,12,false),mat(0xeee8dc));root.add(hijr);keyify(hijr,'hijr');
    const maq=new THREE.Group();maq.position.set(7.2,0,3.6);const stone=new THREE.Mesh(new THREE.BoxGeometry(.34,.17,.34),mat(0x8c7551));stone.position.y=.42;maq.add(stone);for(let i=0;i<8;i++){const a=i/8*Math.PI*2,pole=cyl(.035,.045,1.68,0xcaa03e,8);pole.position.set(Math.cos(a)*.56,.92,Math.sin(a)*.56);maq.add(pole)}const base=cyl(.72,.78,.20,0xcaa03e,8);base.position.y=.10;maq.add(base);const top=cyl(.48,.67,.22,0xcaa03e,8);top.position.y=1.78;maq.add(top);const glass=new THREE.Mesh(new THREE.CylinderGeometry(.66,.66,1.55,8),new THREE.MeshPhysicalMaterial({color:0xffffff,transparent:true,opacity:.20,transmission:.82,roughness:.06,depthWrite:false}));glass.position.y=.95;maq.add(glass);root.add(maq);keyify(maq,'maqam');
    const corridor=new THREE.Group();corridor.position.set(24,0,0);root.add(corridor);const floor=box(8.2,.16,42,0xdedbd2);floor.position.y=.10;corridor.add(floor);const roof=box(8.2,.16,42,0xe8e5dc);roof.position.y=4.20;corridor.add(roof);for(let z=-20;z<=20;z+=2.5){[-3.85,3.85].forEach(x=>{const col=cyl(.11,.14,4.0,0xe8e3d8,10);col.position.set(x,2.0,z);corridor.add(col)})}[-4.2,4.2].forEach(z=>{const green=box(8.0,3.7,.16,0x36b27a);green.position.set(0,2.05,z);corridor.add(green)});for(let x=-2.4;x<=2.4;x+=1.2){const lane=box(.045,.03,40,0xb6b3aa);lane.position.set(x,.20,0);corridor.add(lane)}rockCluster(new THREE.Vector3(24,0,-20),'safa');rockCluster(new THREE.Vector3(24,0,20),'marwah');
    const sai=[new THREE.Vector3(24,.38,-19),new THREE.Vector3(24,.38,19),new THREE.Vector3(24,.38,-19)];tube(sai,0x39a878);
    const ruknHit=new THREE.Mesh(new THREE.SphereGeometry(.32,14,10),new THREE.MeshBasicMaterial({transparent:true,opacity:.01,depthWrite:false}));ruknHit.position.set(-2.88,1.25,2.50);ruknHit.userData.key='rukn';root.add(ruknHit);clickable.push(ruknHit);
    const multazamHit=box(1.15,2.0,.10,0x050505);multazamHit.material.transparent=true;multazamHit.material.opacity=.02;multazamHit.position.set(2.15,2.0,2.56);multazamHit.userData.key='multazam';root.add(multazamHit);clickable.push(multazamHit);
    const mizabHit=new THREE.Mesh(new THREE.SphereGeometry(.35,14,10),new THREE.MeshBasicMaterial({transparent:true,opacity:.01,depthWrite:false}));mizabHit.position.set(0,6.45,-3.35);mizabHit.userData.key='mizab';root.add(mizabHit);clickable.push(mizabHit);
    [['kaaba',new THREE.Vector3(0,0,0)],['blackstone',new THREE.Vector3(3.1,0,2.8)],['rukn',new THREE.Vector3(-3.1,0,2.8)],['multazam',new THREE.Vector3(2.0,0,3.2)],['hijr',new THREE.Vector3(0,0,-6.5)],['mizab',new THREE.Vector3(0,0,-4.4)],['maqam',new THREE.Vector3(7.2,0,3.6)],['safa',new THREE.Vector3(24,0,-20)],['marwah',new THREE.Vector3(24,0,20)]].forEach(([k,p])=>marker(k,p,DATA.haram[k].n[lang==='en'?0:1]));
    for(let i=0;i<34;i++){const pilgrim=sph(.10,0xffffff);pilgrim.userData.t=i/34;pilgrim.userData.pilgrim=true;root.add(pilgrim)}Q('#scaleLabel').textContent='50 m'}`;
  const accurateReset = String.raw`function resetView(){if(mode==='hajj'){camera.position.set(0,88,-118);controls.target.set(0,0,2);controls.minDistance=18;controls.maxDistance=190}else{camera.position.set(48,42,-60);controls.target.set(10,0,0);controls.minDistance=7;controls.maxDistance=115}controls.update()}`;

  const additions = String.raw`
DATA.haram.rukn={n:['Rukn al-Yamani','રુકને યમાની'],a:'الرُّكْن اليَمَانِي',day:'Tawaf landmark',d:['South-western corner of the Kaaba','કાબાનો દક્ષિણ-પશ્ચિમ ખૂણો'],i:['This marker identifies Rukn al-Yamani in its correct corner relationship to Hajar al-Aswad.','આ નિશાની હજરે અસ્વદની સરખામણીમાં રુકને યમાનીનું યોગ્ય સ્થાન બતાવે છે.'],t:[['Identify the corner correctly during Tawaf.','Follow the uploaded guide and never push or harm anyone.'],['તવાફ દરમિયાન ખૂણો સાચી રીતે ઓળખો.','અપલોડ કરેલ પુસ્તક અનુસરો અને ધક્કામુક્કી ન કરો.']],f:[['The selection marker is transparent; the visible geometry remains part of the Kaaba.'],['પસંદગીનું માર્કર પારદર્શક છે; દેખાતી રચના કાબાનો જ ભાગ છે.']],dua:['','',''],p:[P.kaaba]};
DATA.haram.multazam={n:['Multazam','મુલતઝમ'],a:'المُلْتَزَم',day:'Kaaba landmark',d:['Area between the door and Hajar al-Aswad','દરવાજા અને હજરે અસ્વદ વચ્ચેનો ભાગ'],i:['The model separates the Multazam area from the door and Black Stone corner for accurate orientation.','મોડેલ યોગ્ય દિશા માટે મુલતઝમને દરવાજા અને હજરે અસ્વદના ખૂણાથી અલગ બતાવે છે.'],t:[['Use this marker for orientation.','Follow the uploaded guide and crowd-control instructions.'],['આ નિશાનીનો ઉપયોગ સ્થાન ઓળખવા માટે કરો.','અપલોડ કરેલ પુસ્તક અને ભીડ નિયંત્રણ સૂચનાઓ અનુસરો.']],f:[['This is an educational locator, not a reserved standing zone.'],['આ શૈક્ષણિક સ્થાન સૂચક છે, અનામત ઊભા રહેવાની જગ્યા નથી.']],dua:['','',''],p:[P.kaaba]};
DATA.haram.mizab={n:['Mizab al-Rahmah','મીઝાબે રહમત'],a:'مِيزَاب الرَّحْمَة',day:'Kaaba landmark',d:['Roof spout above Hijr Ismail','હિજ્રે ઇસ્માઈલ ઉપરની છતનો પરનાળો'],i:['The gold rain spout projects from the roof toward Hijr Ismail.','સોનેરી પરનાળો છત પરથી હિજ્રે ઇસ્માઈલ તરફ નીકળે છે.'],t:[['Use this landmark to understand the Hijr side of the Kaaba.'],['કાબાની હિજ્રવાળી બાજુ સમજવા આ નિશાનીનો ઉપયોગ કરો.']],f:[['Its placement is aligned with the centre of the Hijr-facing wall.'],['તેનું સ્થાન હિજ્ર તરફની દિવાલના મધ્ય સાથે ગોઠવેલું છે.']],dua:['','',''],p:[P.kaaba]};
`;

  async function start(){
    try{
      if(!window.WebGLRenderingContext)throw new Error('WebGL is disabled or unavailable in this browser. Enable hardware acceleration or open the site in the latest Chrome browser.');
      const engine=await loadEngine();status('Preparing precision sacred-sites model…',`3D engine loaded from ${engine.source}. Rebuilding spacing, orientation and landmark geometry.`);
      const response=await fetch('./app-v5.js?v=10',{cache:'no-store'});if(!response.ok)throw new Error(`Application file returned HTTP ${response.status}`);let code=await response.text();
      code=code
        .replace(/^\s*import\s+\*\s+as\s+THREE\s+from\s+['"][^'"]+['"];?\s*$/m,'')
        .replace(/^\s*import\s+\{\s*OrbitControls\s*\}\s+from\s+['"][^'"]+['"];?\s*$/m,'')
        .replace(/\.n\[lang\]/g,".n[lang==='en'?0:1]")
        .replace(/\.i\[lang\]/g,".i[lang==='en'?0:1]")
        .replace(/\.d\[lang\]/g,".d[lang==='en'?0:1]")
        .replace(/\.t\[lang\]/g,".t[lang==='en'?0:1]")
        .replace(/\.f\[lang\]/g,".f[lang==='en'?0:1]")
        .replace(/function project\(lat,lon\)\{[\s\S]*?\}\nfunction label\(text,key,p\)\{[\s\S]*?\}\nfunction marker/,accurateProject+'\n'+accurateLabel+'\nfunction marker')
        .replace(/function marker\(key,p,text\)\{[\s\S]*?\}\nfunction keyify/,accurateMarker+'\nfunction keyify')
        .replace(/function terrain\(\)\{[\s\S]*?\}\nfunction kaaba/,accurateTerrain+'\nfunction kaaba')
        .replace(/function kaaba\(p,s=1,key='haram'\)\{[\s\S]*?\}\nfunction city/,enhancedKaaba+'\nfunction city')
        .replace(/function city\(p\)\{[\s\S]*?\}\nfunction tents/,accurateCity+'\nfunction tents')
        .replace(/function tents\(p\)\{[\s\S]*?\}\nfunction arafah/,accurateTents+'\nfunction arafah')
        .replace(/function arafah\(p\)\{[\s\S]*?\}\nfunction muz/,accurateArafah+'\nfunction muz')
        .replace(/function muz\(p\)\{[\s\S]*?\}\nfunction jamarat/,accurateMuz+'\nfunction jamarat')
        .replace(/function jamarat\(p\)\{[\s\S]*?\}\nfunction tube/,accurateJamarat+'\nfunction tube')
        .replace(/function buildHajj\(\)\{[\s\S]*?\}\nfunction rockCluster/,accurateBuildHajj+'\nfunction rockCluster')
        .replace(/function buildHaram\(\)\{[\s\S]*?\}\nfunction resetGroups/,accurateBuildHaram+'\nfunction resetGroups')
        .replace(/function resetView\(\)\{[\s\S]*?\}\nfunction setUI/,accurateReset+'\nfunction setUI')
        .replace(/\nlet lang=/,additions+'\nlet lang=');
      const run=new Function('THREE','OrbitControls',`${code}\n//# sourceURL=app-v10-runtime.js`);run(engine.THREE,engine.OrbitControls);
    }catch(error){console.error('3D startup failed:',error);const detail=error?.stack?`${error.message}<br><small style="opacity:.7">${String(error.stack).split('\n').slice(0,4).join('<br>')}</small>`:(error?.message||String(error));status('3D map could not start',detail,true)}
  }
  start();
})();
