import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {T,H,M,daySets} from './data.js';
let lang='en',mode='hajj',selected='haram',scene,camera,renderer,controls,clock,raycaster,mouse,root,labels=[],clickables=[],routeCurve,traveller,routePlaying=false,routeT=0,labelsVisible=true,focusTarget=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const completed=JSON.parse(localStorage.getItem('hu3d_completed')||'{}');
const notes=JSON.parse(localStorage.getItem('hu3d_notes')||'{}');

function init(){
 scene=new THREE.Scene(); scene.fog=new THREE.FogExp2(0x0a3b34,.012);
 camera=new THREE.PerspectiveCamera(48,1,.1,300); camera.position.set(0,36,46);
 renderer=new THREE.WebGLRenderer({antialias:true,alpha:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; renderer.outputColorSpace=THREE.SRGBColorSpace; $('#stage').prepend(renderer.domElement);
 controls=new OrbitControls(camera,renderer.domElement); controls.enableDamping=true; controls.dampingFactor=.06; controls.minDistance=12; controls.maxDistance=95; controls.maxPolarAngle=Math.PI/2.08; controls.target.set(0,0,0);
 scene.add(new THREE.HemisphereLight(0xc9fff1,0x7a5d39,2.1)); const sun=new THREE.DirectionalLight(0xfff1c6,3.2);sun.position.set(-25,40,15);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);
 const rim=new THREE.DirectionalLight(0x6cd8c2,1.2);rim.position.set(30,20,-25);scene.add(rim);
 raycaster=new THREE.Raycaster();mouse=new THREE.Vector2();clock=new THREE.Clock();
 renderer.domElement.addEventListener('pointerdown',onPick); window.addEventListener('resize',resize);resize();buildMode();animate();setTimeout(()=>$('#loading').classList.add('hide'),600);
}
function mat(c,rough=.7,metal=.05){return new THREE.MeshStandardMaterial({color:c,roughness:rough,metalness:metal})}
function shadow(o){o.traverse?.(x=>{if(x.isMesh){x.castShadow=true;x.receiveShadow=true}});return o}
function box(w,h,d,c){return shadow(new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c)))}
function cyl(r1,r2,h,c,seg=24){return shadow(new THREE.Mesh(new THREE.CylinderGeometry(r1,r2,h,seg),mat(c)))}
function disc(r,c,y=.03){const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,.15,64),mat(c));m.position.y=y;m.receiveShadow=true;return m}
function labelSprite(text,key){const can=document.createElement('canvas'),ctx=can.getContext('2d');can.width=512;can.height=128;ctx.fillStyle='rgba(5,48,40,.9)';roundRect(ctx,8,8,496,112,26);ctx.fill();ctx.strokeStyle='rgba(217,181,93,.9)';ctx.lineWidth=4;ctx.stroke();ctx.fillStyle='#fff';ctx.font='700 34px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,256,64);const tex=new THREE.CanvasTexture(can);tex.colorSpace=THREE.SRGBColorSpace;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,depthTest:false}));s.scale.set(8,2,1);s.userData={key,label:true};labels.push(s);return s}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect?ctx.roundRect(x,y,w,h,r):(ctx.rect(x,y,w,h));}
function marker(key,pos,text){const g=new THREE.Group();g.position.set(...pos);const ring=new THREE.Mesh(new THREE.TorusGeometry(1.15,.12,12,40),new THREE.MeshBasicMaterial({color:0xd9b55d}));ring.rotation.x=Math.PI/2;ring.position.y=.18;const orb=new THREE.Mesh(new THREE.SphereGeometry(.55,24,18),new THREE.MeshStandardMaterial({color:0xffe49a,emissive:0x6b4d13,emissiveIntensity:.7}));orb.position.y=1.05;orb.userData={key,clickable:true};clickables.push(orb);g.add(ring,orb);const l=labelSprite(text,key);l.position.y=3.2;g.add(l);root.add(g);g.userData.pulse=ring;return g}
function route(points,color=0xe2bd61){const curve=new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(...p)),false,'centripetal');const tube=new THREE.Mesh(new THREE.TubeGeometry(curve,180,.14,10,false),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.88}));tube.position.y=.18;root.add(tube);return curve}
function clearRoot(){if(root){scene.remove(root);root.traverse(o=>{o.geometry?.dispose();if(o.material){Array.isArray(o.material)?o.material.forEach(m=>m.dispose()):o.material.dispose()}})}root=new THREE.Group();scene.add(root);labels=[];clickables=[];routeCurve=null;traveller=null;routeT=0;$('#routeSlider').value=0}
function buildMode(){clearRoot(); if(mode==='hajj')buildHajj();else buildHaram();buildLegend();updateStatic();selectLocation(mode==='hajj'?'haram':'kaaba',false);resetCamera()}
function ground(size,color){const g=new THREE.Mesh(new THREE.PlaneGeometry(size,size,80,80),mat(color,1));g.rotation.x=-Math.PI/2;g.receiveShadow=true;root.add(g);for(let i=0;i<55;i++){const r=.3+Math.random()*.8;const rock=new THREE.Mesh(new THREE.DodecahedronGeometry(r,0),mat(0x826f54,1));rock.position.set((Math.random()-.5)*size,.15,(Math.random()-.5)*size);rock.scale.y=.3+Math.random()*.45;root.add(rock)}}
function buildKaaba(pos=[0,0,0],scale=1){const g=new THREE.Group();g.position.set(...pos);g.scale.setScalar(scale);const k=box(5.5,6.5,5.2,0x121212);k.position.y=3.25;g.add(k);const band=box(5.62,.72,5.32,0xd1a33e);band.position.y=4.85;g.add(band);const door=box(1.3,2.7,.12,0xd8ad4b);door.position.set(1.2,2.0,2.66);g.add(door);root.add(g);return g}
function buildHajj(){ground(90,0xb99f72);const city=disc(13,0xe8e1cf);city.position.set(-23,.05,2);root.add(city);buildKaaba([-23,.1,2],.63);for(let i=0;i<16;i++){const b=box(1+Math.random()*1.5,1+Math.random()*3,1+Math.random()*1.5,[0xd9d2c1,0xc8c1b3,0xe8dfcb][i%3]);b.position.set(-23+(Math.random()-.5)*18,.5+(b.geometry.parameters.height||1)/2,2+(Math.random()-.5)*16);root.add(b)}
 const minaBase=disc(9,0xcab78e);minaBase.position.set(-8,.04,0);root.add(minaBase);for(let x=-13;x<-3;x+=2.1)for(let z=-5;z<6;z+=2.1){const tent=cyl(.85,0,1.7,0xf7f3e7,18);tent.position.set(x,.85,z);root.add(tent)}
 const ap=disc(10,0xd0b783);ap.position.set(15,.04,-8);root.add(ap);const mount=cyl(4.2,1.2,4.5,0x8f7652,8);mount.position.set(18,2.25,-10);mount.scale.z=.7;root.add(mount);for(let i=0;i<8;i++){const pole=cyl(.08,.08,4.5,0xeeeeee,10);pole.position.set(10+Math.random()*10,2.25,-13+Math.random()*10);root.add(pole)}
 const mp=disc(8,0x927f61);mp.position.set(4,.04,7);root.add(mp);for(let i=0;i<12;i++){const lamp=cyl(.08,.1,2.2,0x3d3d3d,10);lamp.position.set(-2+Math.random()*12,1.1,2+Math.random()*10);const glow=new THREE.PointLight(0xffcf72,.7,5);glow.position.set(lamp.position.x,2.25,lamp.position.z);root.add(lamp,glow)}
 const bridge=box(8,.8,4,0xb6b7b3);bridge.position.set(-5,1.1,3);root.add(bridge);[-2.2,0,2.2].forEach(x=>{const p=box(.55,3.4,1.1,0xe7e4dc);p.position.set(-5+x,2.3,3);root.add(p)});
 routeCurve=route([[-23,.4,2],[-15,.4,1],[-8,.4,0],[2,.4,-4],[15,.4,-8],[9,.4,0],[4,.4,7],[-2,.4,5],[-5,.4,3],[-14,.4,2],[-23,.4,2]]);
 traveller=new THREE.Mesh(new THREE.SphereGeometry(.38,20,16),new THREE.MeshStandardMaterial({color:0xffffff,emissive:0x2d9b84,emissiveIntensity:1.4}));traveller.position.copy(routeCurve.getPoint(0));traveller.position.y=1.15;root.add(traveller);
 const points=[['haram',[-23,0,2]],['mina',[-8,0,0]],['arafah',[15,0,-8]],['muz',[4,0,7]],['jamarat',[-5,0,3]],['haramReturn',[-21,0,1]],['farewell',[-25,0,-1]]];points.forEach(([k,p])=>marker(k,p,H[k].name[lang]));
 addDistanceLabel('≈ 7 km',[-15,1.4,1]);addDistanceLabel('≈ 14 km',[3,1.4,-4]);addDistanceLabel('≈ 9 km',[10,1.4,0]);addDistanceLabel('≈ 7 km',[-14,1.4,4]);
 $('#journeyCtl').style.display='flex';
}
function addDistanceLabel(text,pos){const s=labelSprite(text,'');s.scale.set(4.3,1.1,1);s.position.set(...pos);root.add(s)}
function buildHaram(){ground(70,0xe9e7df);const marble=new THREE.Mesh(new THREE.CircleGeometry(28,96),new THREE.MeshStandardMaterial({color:0xf7f6f1,roughness:.45,metalness:.02}));marble.rotation.x=-Math.PI/2;marble.position.y=.03;marble.receiveShadow=true;root.add(marble);for(let r=8;r<=25;r+=4){const ring=new THREE.Mesh(new THREE.RingGeometry(r-.03,r+.03,128),new THREE.MeshBasicMaterial({color:0xcfcac0,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=.05;root.add(ring)}buildKaaba([0,.1,0],1);
 for(let r=6.7;r<=11;r+=2.1){const t=new THREE.Mesh(new THREE.TorusGeometry(r,.035,8,100),new THREE.MeshBasicMaterial({color:0xd9b55d,transparent:true,opacity:.45}));t.rotation.x=Math.PI/2;t.position.y=.12;root.add(t)}
 const corridor=box(33,.18,5.5,0xdedbd2);corridor.position.set(0,.12,-4);root.add(corridor);const safa=cyl(2.4,3.3,2.5,0x8f7b5c,24);safa.position.set(-16.5,1.25,-4);safa.scale.z=.75;root.add(safa);const marwa=cyl(2.4,3.3,2.5,0x8f7b5c,24);marwa.position.set(16.5,1.25,-4);marwa.scale.z=.75;root.add(marwa);const green1=box(.25,3.4,5.8,0x44b97e);green1.position.set(-3.2,1.8,-4);root.add(green1);const green2=box(.25,3.4,5.8,0x44b97e);green2.position.set(3.2,1.8,-4);root.add(green2);
 const maq=cyl(.7,.7,2.6,0xd3a544,24);maq.position.set(0,1.3,5.5);root.add(maq);const glass=new THREE.Mesh(new THREE.CylinderGeometry(1.05,1.05,3.2,32),new THREE.MeshPhysicalMaterial({color:0xffffff,transparent:true,opacity:.25,roughness:.1,transmission:.7}));glass.position.set(0,1.6,5.5);root.add(glass);
 const z=box(2.2,.35,2.2,0x76a7a0);z.position.set(5,.3,4);root.add(z);
 const arch=cyl(1.7,1.7,.35,0xd9b55d,36);arch.rotation.z=Math.PI/2;arch.position.set(18,2.5,4);root.add(arch);
 routeCurve=route([[-15,.3,-4],[-8,.3,-4],[0,.3,-4],[8,.3,-4],[15,.3,-4],[8,.3,-4],[0,.3,-4],[-8,.3,-4],[-15,.3,-4]],0x51b783);
 traveller=new THREE.Mesh(new THREE.SphereGeometry(.35,20,16),new THREE.MeshStandardMaterial({color:0xffffff,emissive:0x38a77f,emissiveIntensity:1.5}));traveller.position.copy(routeCurve.getPoint(0));traveller.position.y=1.1;root.add(traveller);
 [['kaaba',[0,0,0]],['blackstone',[2.8,0,2.4]],['rukn',[-2.8,0,2.4]],['maqam',[0,0,5.5]],['zamzam',[5,0,4]],['safa',[-15,0,-4]],['marwah',[15,0,-4]],['hair',[18,0,4]]].forEach(([k,p])=>marker(k,p,M[k].name[lang]));addDistanceLabel('≈ 394 m one way',[0,1.6,-4]);$('#journeyCtl').style.display='flex';
}
function buildLegend(){const data=mode==='hajj'?H:M;$('#legend').innerHTML=Object.keys(data).map(k=>`<button data-key="${k}">${data[k].name[lang]}</button>`).join('');$('#legend').querySelectorAll('button').forEach(b=>b.onclick=()=>selectLocation(b.dataset.key))}
function updateStatic(){const t=T[lang];$('#sceneName').textContent=mode==='hajj'?t.sceneH:t.sceneM;$('#sceneHint').textContent=t.hint;$('#panelKicker').textContent=t.selected;$('#progressLabel').textContent=t.progress;$('#dayTitle').textContent=t.day;$('#tasksTitle').textContent=t.tasks;$('#duaTitle').textContent=t.dua;$('#routeTitle').textContent=t.route;$('#speakBtn').textContent=t.listen;$('#focusBtn').textContent=t.focus;$('#notesBtn').textContent=t.note;$('#openPanel').textContent=t.open;$('#playRoute').textContent=routePlaying?t.stopBtn:t.routeBtn;$$('[data-mode]').forEach(b=>b.textContent=b.dataset[lang]);}
function selectLocation(key,focus=true){selected=key;const d=(mode==='hajj'?H:M)[key];if(!d)return;$('#panelTitle').textContent=d.name[lang];$('#distance').textContent='📍 '+d.dist[lang];$('#panelIntro').textContent=d.intro[lang];$('#tasks').innerHTML=d.tasks[lang].map((x,i)=>`<div class="task"><i>${i+1}</i><span>${x}</span></div>`).join('');$('#arabic').textContent=d.dua[0];$('#trans').textContent=d.dua[1];$('#meaning').textContent=d.dua[2];$('#duaSection').style.display=d.dua[0]?'block':'none';$('#completeBtn').textContent=completed[mode+':'+key]?T[lang].completed:T[lang].complete;$('#completeBtn').classList.toggle('gold',!completed[mode+':'+key]);$$('#legend button').forEach(b=>b.classList.toggle('on',b.dataset.key===key));renderDays();renderMiniRoute();updateProgress();if(focus)focusLocation(key);if(innerWidth<=980)$('#panel').classList.add('open')}
function renderDays(){if(mode!=='hajj'){$('#daySection').style.display='none';return}$('#daySection').style.display='block';const d=H[selected];$('#daystrip').innerHTML=Object.keys(daySets).map(day=>`<button class="${d.day===day||daySets[day].includes(selected)?'on':''}" data-day="${day}">${day}</button>`).join('');$('#daystrip').querySelectorAll('button').forEach(b=>b.onclick=()=>{const first=daySets[b.dataset.day][0];selectLocation(first)})}
function renderMiniRoute(){const rows=mode==='hajj'?[['Kaaba → Mina','≈ 7 km'],['Mina → Arafah','≈ 14 km'],['Arafah → Muzdalifah','≈ 9 km'],['Muzdalifah → Mina','≈ 7 km']]:[['Safa → Marwah','≈ 394 m'],['7 Sa‘i laps','≈ 2.8 km'],['Tawaf distance','Varies by level & radius']];$('#miniRoute').innerHTML=rows.map(r=>`<div class="routeRow"><div class="dot"></div><b>${r[0]}</b><span>${r[1]}</span></div>`).join('')}
function updateProgress(){const keys=Object.keys(mode==='hajj'?H:M);const done=keys.filter(k=>completed[mode+':'+k]).length;const p=Math.round(done/keys.length*100);$('#progressValue').textContent=p+'%';$('#progressBar').style.width=p+'%'}
function focusLocation(key){const d=(mode==='hajj'?H:M)[key];if(!d)return;const p=new THREE.Vector3(...d.pos);focusTarget={target:p.clone(),cam:p.clone().add(new THREE.Vector3(mode==='hajj'?10:8,mode==='hajj'?12:9,mode==='hajj'?15:12)),t:0}}
function resetCamera(){focusTarget={target:new THREE.Vector3(0,0,0),cam:new THREE.Vector3(0,mode==='hajj'?36:30,mode==='hajj'?46:40),t:0}}
function onPick(e){const r=renderer.domElement.getBoundingClientRect();mouse.x=(e.clientX-r.left)/r.width*2-1;mouse.y=-((e.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(mouse,camera);const hit=raycaster.intersectObjects(clickables,false)[0];if(hit?.object.userData.key)selectLocation(hit.object.userData.key)}
function resize(){const w=$('#stage').clientWidth,h=$('#stage').clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)}
function animate(){requestAnimationFrame(animate);const dt=clock.getDelta();controls.update();if(focusTarget){focusTarget.t=Math.min(1,focusTarget.t+dt*1.6);const s=1-Math.pow(1-focusTarget.t,3);camera.position.lerp(focusTarget.cam,s*.14);controls.target.lerp(focusTarget.target,s*.14);if(focusTarget.t>=1)focusTarget=null}root?.traverse(o=>{if(o.userData.pulse){const v=1+Math.sin(performance.now()*.004)*.12;o.userData.pulse.scale.set(v,v,v)}});if(routePlaying){routeT=(routeT+dt*.045)%1;$('#routeSlider').value=Math.round(routeT*100);moveTraveller(routeT)}renderer.render(scene,camera)}
function moveTraveller(t){if(routeCurve&&traveller){const p=routeCurve.getPoint(t);traveller.position.copy(p);traveller.position.y=1.05}}
function setLang(l){lang=l;$('#en').classList.toggle('on',l==='en');$('#gu').classList.toggle('on',l==='gu');updateStatic();buildLegend();selectLocation(selected,false);const old=[...labels];old.forEach(s=>{if(!s.userData.key)return;const d=(mode==='hajj'?H:M)[s.userData.key];if(d){const p=s.position.clone(),parent=s.parent;parent.remove(s);const n=labelSprite(d.name[lang],s.userData.key);n.position.copy(p);parent.add(n)}})}
$('#en').onclick=()=>setLang('en');$('#gu').onclick=()=>setLang('gu');$$('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;$$('[data-mode]').forEach(x=>x.classList.toggle('on',x===b));routePlaying=false;buildMode()});$('#homeCam').onclick=resetCamera;$('#toggleLabels').onclick=()=>{labelsVisible=!labelsVisible;labels.forEach(l=>l.visible=labelsVisible)};$('#playRoute').onclick=()=>{routePlaying=!routePlaying;$('#playRoute').textContent=routePlaying?T[lang].stopBtn:T[lang].routeBtn};$('#routeSlider').oninput=e=>{routePlaying=false;routeT=e.target.value/100;moveTraveller(routeT);$('#playRoute').textContent=T[lang].routeBtn};$('#focusBtn').onclick=()=>focusLocation(selected);$('#completeBtn').onclick=()=>{const k=mode+':'+selected;completed[k]=!completed[k];localStorage.setItem('hu3d_completed',JSON.stringify(completed));selectLocation(selected,false)};$('#speakBtn').onclick=()=>{speechSynthesis.cancel();const d=(mode==='hajj'?H:M)[selected];const u=new SpeechSynthesisUtterance(d.name[lang]+'. '+d.intro[lang]+'. '+d.tasks[lang].join('. '));u.lang=lang==='gu'?'gu-IN':'en-GB';speechSynthesis.speak(u)};$('#notesBtn').onclick=()=>{const k=mode+':'+selected;const v=prompt(lang==='gu'?'આ સ્થળ માટે તમારી ખાનગી નોંધ:':'Your private note for this location:',notes[k]||'');if(v!==null){notes[k]=v;localStorage.setItem('hu3d_notes',JSON.stringify(notes))}};$('#openPanel').onclick=()=>$('#panel').classList.add('open');$('#closePanel').onclick=()=>$('#panel').classList.remove('open');
init();