export const T={
 en:{sceneH:'Makkah and the Sacred Sites',sceneM:'Masjid al-Haram learning model',hint:'Drag to rotate • Scroll to zoom • Click any location',selected:'SELECTED LOCATION',progress:'Journey progress',day:'Hajj day timeline',tasks:'What to do here',dua:'Relevant dua / dhikr',route:'Route and distance',complete:'✓ Mark location complete',completed:'✓ Completed',listen:'🔊 Listen',focus:'◎ Focus in 3D',note:'✎ Private note',open:'Open guide',approx:'Approx.',start:'Starting point',routeBtn:'▶ Route',stopBtn:'❚❚ Pause'},
 gu:{sceneH:'મક્કા અને હજના પવિત્ર સ્થળો',sceneM:'મસ્જિદુલ હરામ શીખવા માટેનું મોડેલ',hint:'ફેરવવા ખેંચો • ઝૂમ કરો • કોઈપણ સ્થળ પર ક્લિક કરો',selected:'પસંદ કરેલું સ્થળ',progress:'સફરની પ્રગતિ',day:'હજના દિવસોની સમયરેખા',tasks:'અહીં શું કરવું',dua:'સંબંધિત દુઆ / ઝિક્ર',route:'માર્ગ અને અંતર',complete:'✓ સ્થળ પૂર્ણ તરીકે નોંધો',completed:'✓ પૂર્ણ થયું',listen:'🔊 સાંભળો',focus:'◎ 3D માં જુઓ',note:'✎ ખાનગી નોંધ',open:'માર્ગદર્શન ખોલો',approx:'અંદાજે',start:'શરૂઆતનું સ્થળ',routeBtn:'▶ માર્ગ',stopBtn:'❚❚ થોભો'}
};
export const H={
 haram:{name:{en:'Masjid al-Haram & Kaaba',gu:'મસ્જિદુલ હરામ અને કાબા'},dist:{en:'Starting point',gu:'શરૂઆતનું સ્થળ'},intro:{en:'The Hajj route begins from Makkah. Before leaving for Mina, be in Ihram for Hajj, make the intention and recite the Talbiyah.',gu:'હજનો માર્ગ મક્કાથી શરૂ થાય છે. મીના જતાં પહેલાં હજનો ઇહરામ બાંધો, નિયત કરો અને તલ્બિયહ પઢો.'},tasks:{en:['Enter Ihram for Hajj according to your Hajj type.','Make the intention in the heart and begin the Talbiyah.','Prepare only what is needed and leave for Mina with your group.'],gu:['તમારા હજના પ્રકાર મુજબ હજનો ઇહરામ બાંધો.','દિલમાં નિયત કરો અને તલ્બિયહ શરૂ કરો.','જરૂરી સામાન તૈયાર કરી તમારા જૂથ સાથે મીના તરફ જાઓ.']},dua:['لَبَّيْكَ اللَّهُمَّ لَبَّيْكَ، لَبَّيْكَ لَا شَرِيكَ لَكَ لَبَّيْكَ','Labbayk Allahumma labbayk, labbayka la sharika laka labbayk.','હાજર છું, હે અલ્લાહ! હું હાજર છું. આપનો કોઈ ભાગીદાર નથી; હું હાજર છું.'],pos:[-24,1,3],day:'8 Dhul-Hijjah'},
 mina:{name:{en:'Mina',gu:'મીના'},dist:{en:'Approx. 7 km from the Kaaba',gu:'કાબાથી અંદાજે 7 કિમી'},intro:{en:'Mina is the tent city where pilgrims stay before Arafah and again during the Days of Tashriq.',gu:'મીના તંબુઓનું શહેર છે. અહીં હજયાત્રીઓ અરફાત પહેલાં અને પછી તશરીકના દિવસોમાં રોકાય છે.'},tasks:{en:['On 8 Dhul-Hijjah, travel to Mina while reciting Talbiyah.','Pray Dhuhr, Asr, Maghrib, Isha and Fajr in Mina at their times, shortening the four-rak‘ah prayers.','Spend the night in Mina and leave for Arafah after sunrise on the 9th.'],gu:['8 ઝુલહિજ્જાએ તલ્બિયહ પઢતા મીના જાઓ.','મીનામાં ઝુહર, અસર, મગરીબ, ઇશા અને ફજર સમયસર પઢો; ચાર રકઅતવાળી નમાઝ કસર કરો.','રાત મીનામાં રોકાઈ 9મીના સૂર્યોદય પછી અરફાત જાઓ.']},dua:['لَبَّيْكَ اللَّهُمَّ لَبَّيْكَ','Labbayk Allahumma labbayk.','હે અલ્લાહ! હું હાજર છું.'],pos:[-9,1,-1],day:'8 Dhul-Hijjah'},
 arafah:{name:{en:'Arafah',gu:'અરફાત'},dist:{en:'Approx. 14 km from Mina',gu:'મીનાથી અંદાજે 14 કિમી'},intro:{en:'Standing at Arafah on 9 Dhul-Hijjah is the central pillar of Hajj. Use this time for sincere dua, repentance and remembrance of Allah.',gu:'9 ઝુલહિજ્જાએ અરફાતમાં વુકૂફ હજનો મુખ્ય રુકન છે. આ સમય દિલથી દુઆ, તૌબા અને અલ્લાહના ઝિક્રમાં પસાર કરો.'},tasks:{en:['Remain within the boundary of Arafah until sunset.','Pray Dhuhr and Asr as instructed for the Hajj gathering.','Face the Qiblah, raise your hands and make abundant personal dua and dhikr.','Do not leave Arafah before sunset.'],gu:['સૂર્યાસ્ત સુધી અરફાતની હદમાં રહો.','હજની જમાતની વ્યવસ્થા મુજબ ઝુહર અને અસર અદા કરો.','કિબલા તરફ થઈ હાથ ઊંચા કરી ઘણી દુઆ અને ઝિક્ર કરો.','સૂર્યાસ્ત પહેલાં અરફાત ન છોડો.']},dua:['لَا إِلٰهَ إِلَّا اللّٰهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ','La ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamd, wa huwa ‘ala kulli shay’in qadir.','અલ્લાહ સિવાય કોઈ સાચો ઉપાસ્ય નથી; તે એકલો છે, તેનો કોઈ ભાગીદાર નથી.'],pos:[15,1,-8],day:'9 Dhul-Hijjah'},
 muz:{name:{en:'Muzdalifah',gu:'મુઝદલિફા'},dist:{en:'Approx. 9 km from Arafah',gu:'અરફાતથી અંદાજે 9 કિમી'},intro:{en:'After sunset at Arafah, pilgrims travel calmly to Muzdalifah, pray, rest and prepare for the next day.',gu:'અરફાતમાં સૂર્યાસ્ત પછી હજયાત્રીઓ શાંતિથી મુઝદલિફા જાય છે, નમાઝ પઢે છે, આરામ કરે છે અને આગળના દિવસ માટે તૈયારી કરે છે.'},tasks:{en:['Leave Arafah after sunset without praying Maghrib there.','Pray Maghrib and Isha in Muzdalifah according to the Hajj method.','Spend the night, pray Fajr and remember Allah.','Collect suitable small pebbles without causing crowding or harm.'],gu:['સૂર્યાસ્ત પછી અરફાત છોડો; ત્યાં મગરીબ ન પઢો.','મુઝદલિફામાં હજની રીત મુજબ મગરીબ અને ઇશા પઢો.','રાત રોકાઓ, ફજર પઢો અને અલ્લાહનો ઝિક્ર કરો.','ભીડ કે નુકસાન કર્યા વગર યોગ્ય નાની કાંકરીઓ મેળવો.']},dua:['فَاذْكُرُوا اللَّهَ عِنْدَ الْمَشْعَرِ الْحَرَامِ','Remember Allah at al-Mash‘ar al-Haram.','મશઅરુલ હરામ પાસે અલ્લાહનો ઝિક્ર કરો.'],pos:[4,1,7],day:'Night of 9th'},
 jamarat:{name:{en:'Jamarat',gu:'જમરાત'},dist:{en:'In Mina; route varies by camp',gu:'મીનામાં; કેમ્પ મુજબ માર્ગ બદલાય છે'},intro:{en:'The Jamarat complex is where the prescribed stoning is performed on the correct days and in the correct order.',gu:'જમરાત કોમ્પ્લેક્સમાં નક્કી દિવસો અને નક્કી ક્રમ મુજબ રમી કરવામાં આવે છે.'},tasks:{en:['On the 10th, stone Jamrat al-‘Aqabah with seven pebbles.','Say “Allahu Akbar” with each pebble.','On the 11th–13th, stone the three Jamarat in the prescribed order and time.','Follow official crowd-control routes and never push or endanger others.'],gu:['10મીના જમરતુલ અકબા પર સાત કાંકરી મારો.','દરેક કાંકરી સાથે “અલ્લાહુ અકબર” કહો.','11થી 13મી દરમિયાન નક્કી ક્રમ અને સમયમાં ત્રણેય જમરાતને રમી કરો.','સરકારી ભીડ નિયંત્રણ માર્ગ માનો અને કોઈને ધક્કો કે જોખમ ન આપો.']},dua:['اللّٰهُ أَكْبَرُ','Allahu Akbar.','અલ્લાહ સૌથી મહાન છે.'],pos:[-5,1,3],day:'10–13 Dhul-Hijjah'},
 haramReturn:{name:{en:'Return to Makkah: Tawaf al-Ifadah',gu:'મક્કા વાપસી: તવાફુલ ઇફાદા'},dist:{en:'Approx. 7 km from Mina',gu:'મીનાથી અંદાજે 7 કિમી'},intro:{en:'After the rites of the 10th, return to Masjid al-Haram for Tawaf al-Ifadah and Sa‘i when required.',gu:'10મીના અમલો પછી તવાફુલ ઇફાદા અને જરૂર હોય તો સઈ માટે મસ્જિદુલ હરામ પર પાછા આવો.'},tasks:{en:['Perform Tawaf al-Ifadah with seven circuits.','Pray two rak‘ahs when possible without blocking people.','Drink Zamzam and perform Sa‘i if it is due for your Hajj type.','Return to Mina for the required nights of Tashriq.'],gu:['સાત ચક્કર સાથે તવાફુલ ઇફાદા કરો.','લોકોને અવરોધ ન થાય તેવી રીતે શક્ય હોય તો બે રકઅત પઢો.','ઝમઝમ પીવો અને તમારા હજના પ્રકાર મુજબ બાકી હોય તો સઈ કરો.','તશરીકની જરૂરી રાતો માટે મીના પર પાછા જાઓ.']},dua:['رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ','Rabbana atina fid-dunya hasanatan wa fil-akhirati hasanatan wa qina ‘adhaban-nar.','હે અમારા રબ! અમને દુનિયામાં ભલાઈ અને આખિરતમાં ભલાઈ આપ અને આગની સજાથી બચાવ.'],pos:[-21,1,1],day:'10 Dhul-Hijjah'},
 farewell:{name:{en:'Farewell Tawaf',gu:'તવાફુલ વિદા'},dist:{en:'Final rite before leaving Makkah',gu:'મક્કા છોડતાં પહેલાં અંતિમ અમલ'},intro:{en:'Before leaving Makkah, perform the Farewell Tawaf when it applies, making the House your final sacred visit.',gu:'મક્કા છોડતાં પહેલાં જ્યાં લાગુ પડે ત્યાં તવાફુલ વિદા કરો અને બૈતુલ્લાહને અંતિમ પવિત્ર મુલાકાત બનાવો.'},tasks:{en:['Complete all remaining obligations before departure.','Perform seven circuits of Farewell Tawaf.','Avoid unnecessary delay in Makkah after the farewell Tawaf.'],gu:['રવાના થવા પહેલાં બાકી ફરજો પૂર્ણ કરો.','તવાફુલ વિદાના સાત ચક્કર કરો.','તવાફુલ વિદા પછી મક્કામાં અનાવશ્યક વિલંબ ન કરો.']},dua:['رَبَّنَا تَقَبَّلْ مِنَّا إِنَّكَ أَنْتَ السَّمِيعُ الْعَلِيمُ','Rabbana taqabbal minna innaka Antas-Sami‘ul-‘Alim.','હે અમારા રબ! અમારી પાસેથી કબૂલ કર; નિશ્ચિત તમે સર્વ સાંભળનાર, સર્વ જાણનાર છો.'],pos:[-25,1,-1],day:'Before departure'}
};
export const M={
 kaaba:{name:{en:'Kaaba',gu:'કાબા'},dist:{en:'Center of Tawaf',gu:'તવાફનું કેન્દ્ર'},intro:{en:'Begin Tawaf aligned with the Black Stone. Keep the Kaaba on your left and complete seven circuits.',gu:'હજરે અસવદની સીધમાં તવાફ શરૂ કરો. કાબાને ડાબી બાજુ રાખી સાત ચક્કર પૂર્ણ કરો.'},tasks:{en:['Make the intention for Tawaf in the heart.','Begin at the Black Stone line and complete seven circuits.','Avoid pushing; gesture toward the Black Stone when you cannot reach it.'],gu:['દિલમાં તવાફની નિયત કરો.','હજરે અસવદની લાઇનથી શરૂ કરી સાત ચક્કર કરો.','ધક્કામુક્કી ન કરો; પહોંચી ન શકાય તો દૂરથી ઈશારો કરો.']},dua:['بِسْمِ اللّٰهِ، اللّٰهُ أَكْبَرُ','Bismillah, Allahu Akbar.','અલ્લાહના નામથી; અલ્લાહ સૌથી મહાન છે.'],pos:[0,1,0]},
 blackstone:{name:{en:'Hajar al-Aswad',gu:'હજરે અસવદ'},dist:{en:'Starting line of each Tawaf circuit',gu:'દરેક તવાફના ચક્કરની શરૂઆતની લાઇન'},intro:{en:'The Black Stone corner marks the beginning and end of every circuit of Tawaf.',gu:'હજરે અસવદનો ખૂણો તવાફના દરેક ચક્કરની શરૂઆત અને અંત દર્શાવે છે.'},tasks:{en:['Face the corner at the start of each circuit.','Touch or kiss only when safely possible.','Otherwise point toward it and say “Allahu Akbar”; do not push.'],gu:['દરેક ચક્કરની શરૂઆતમાં આ ખૂણા તરફ થાઓ.','સુરક્ષિત રીતે શક્ય હોય ત્યારે જ સ્પર્શ કે ચુંબન કરો.','નહીં તો ઈશારો કરી “અલ્લાહુ અકબર” કહો; ધક્કો ન આપો.']},dua:['اللّٰهُ أَكْبَرُ','Allahu Akbar.','અલ્લાહ સૌથી મહાન છે.'],pos:[2.8,1,2.4]},
 rukn:{name:{en:'Rukn Yamani',gu:'રુક્ને યમાની'},dist:{en:'Corner before Hajar al-Aswad',gu:'હજરે અસવદ પહેલાંનો ખૂણો'},intro:{en:'Touch Rukn Yamani when easily possible without pushing. There is no need to point toward it from a distance.',gu:'ધક્કા વિના સહેલાઈથી શક્ય હોય તો રુક્ને યમાનીને સ્પર્શ કરો. દૂરથી તેની તરફ ઈશારો કરવાની જરૂર નથી.'},tasks:{en:['Touch it with the hand when safely possible.','Do not crowd, push or stop the flow.','Recite the well-known Quranic dua between Rukn Yamani and the Black Stone.'],gu:['સુરક્ષિત રીતે શક્ય હોય તો હાથથી સ્પર્શ કરો.','ભીડ, ધક્કો કે રસ્તામાં અવરોધ ન કરો.','રુક્ને યમાની અને હજરે અસવદ વચ્ચે જાણીતી કુરઆની દુઆ પઢો.']},dua:['رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ','Rabbana atina fid-dunya hasanatan wa fil-akhirati hasanatan wa qina ‘adhaban-nar.','હે અમારા રબ! અમને દુનિયા અને આખિરતમાં ભલાઈ આપ અને આગથી બચાવ.'],pos:[-2.8,1,2.4]},
 maqam:{name:{en:'Maqam Ibrahim',gu:'મકામે ઇબ્રાહીમ'},dist:{en:'Near the Kaaba',gu:'કાબા નજીક'},intro:{en:'After Tawaf, pray two rak‘ahs in a suitable place without obstructing Tawaf or other worshippers.',gu:'તવાફ પછી લોકોના માર્ગ કે તવાફમાં અવરોધ ન થાય તેવી યોગ્ય જગ્યાએ બે રકઅત પઢો.'},tasks:{en:['Move away from the Tawaf flow.','Pray two rak‘ahs where space is available.','Do not insist on standing directly behind Maqam Ibrahim when crowded.'],gu:['તવાફના પ્રવાહથી દૂર થાઓ.','જ્યાં જગ્યા મળે ત્યાં બે રકઅત પઢો.','ભીડ હોય ત્યારે મકામે ઇબ્રાહીમની પાછળ જ ઊભા રહેવાનો આગ્રહ ન કરો.']},dua:['وَاتَّخِذُوا مِنْ مَقَامِ إِبْرَاهِيمَ مُصَلًّى','Take the standing place of Ibrahim as a place of prayer.','મકામે ઇબ્રાહીમને નમાઝનું સ્થાન બનાવો.'],pos:[0,1,5.5]},
 zamzam:{name:{en:'Zamzam',gu:'ઝમઝમ'},dist:{en:'Available throughout the Haram',gu:'હરમમાં વિવિધ સ્થળે ઉપલબ્ધ'},intro:{en:'Drink Zamzam with gratitude and make sincere dua. Use the designated drinking points and keep pathways clear.',gu:'શુક્ર સાથે ઝમઝમ પીવો અને દિલથી દુઆ કરો. નક્કી સ્થળોનો ઉપયોગ કરો અને માર્ગ ખુલ્લો રાખો.'},tasks:{en:['Drink calmly and avoid waste.','Make any beneficial dua.','Do not block the movement of worshippers.'],gu:['શાંતિથી પીવો અને બગાડ ન કરો.','કોઈપણ ભલાઈની દુઆ કરો.','ઇબાદત કરનારાઓનો રસ્તો ન રોકો.']},dua:['اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا وَرِزْقًا وَاسِعًا وَشِفَاءً مِنْ كُلِّ دَاءٍ','Allahumma inni as’aluka ‘ilman nafi‘an, wa rizqan wasi‘an, wa shifa’an min kulli da’.','હે અલ્લાહ! હું લાભદાયક જ્ઞાન, વિશાળ રિઝક અને દરેક રોગથી શિફા માગું છું.'],pos:[5,1,4]},
 safa:{name:{en:'Safa',gu:'સફા'},dist:{en:'Beginning of Sa‘i',gu:'સઈની શરૂઆત'},intro:{en:'Sa‘i begins at Safa. Face the Qiblah, praise Allah and make dua before proceeding toward Marwah.',gu:'સઈની શરૂઆત સફાથી થાય છે. કિબલા તરફ થઈ અલ્લાહની પ્રશંસા અને દુઆ કર્યા પછી મરવા તરફ જાઓ.'},tasks:{en:['Recite the verse when approaching Safa.','Face the Qiblah, raise the hands and make dhikr and dua.','Walk toward Marwah; men may move briskly in the marked green-light section.'],gu:['સફા પાસે પહોંચતાં સંબંધિત આયત પઢો.','કિબલા તરફ થઈ હાથ ઊંચા કરી ઝિક્ર અને દુઆ કરો.','મરવા તરફ ચાલો; લીલા નિશાન વચ્ચે પુરુષો ઝડપથી ચાલે.']},dua:['إِنَّ الصَّفَا وَالْمَرْوَةَ مِنْ شَعَائِرِ اللَّهِ','Indeed, Safa and Marwah are among the symbols of Allah.','નિશ્ચિત સફા અને મરવા અલ્લાહની નિશાનીઓમાંથી છે.'],pos:[-15,1,-4]},
 marwah:{name:{en:'Marwah',gu:'મરવા'},dist:{en:'Approx. 394 m from Safa one way',gu:'સફાથી એક તરફ અંદાજે 394 મીટર'},intro:{en:'Reaching Marwah completes one lap. Continue until seven laps are completed, ending at Marwah.',gu:'મરવા પહોંચવાથી એક ચક્કર પૂર્ણ થાય છે. કુલ સાત ચક્કર કરો અને અંત મરવા પર થાય છે.'},tasks:{en:['Repeat the dhikr and dua at Marwah.','Count Safa to Marwah as one lap and Marwah to Safa as the next.','Complete seven laps in total, ending at Marwah.'],gu:['મરવા પર પણ ઝિક્ર અને દુઆ કરો.','સફાથી મરવા એક ચક્કર અને મરવાથી સફા બીજો ચક્કર ગણો.','કુલ સાત ચક્કર પૂર્ણ કરો અને અંત મરવા પર કરો.']},dua:['لَا إِلٰهَ إِلَّا اللّٰهُ وَحْدَهُ لَا شَرِيكَ لَهُ','La ilaha illallahu wahdahu la sharika lah.','અલ્લાહ સિવાય કોઈ સાચો ઉપાસ્ય નથી; તે એકલો છે, તેનો કોઈ ભાગીદાર નથી.'],pos:[15,1,-4]},
 hair:{name:{en:'Halq or Qasr',gu:'હલક અથવા કસર'},dist:{en:'After completing Sa‘i',gu:'સઈ પૂર્ણ કર્યા પછી'},intro:{en:'After Umrah Sa‘i, men shave or shorten the hair and women cut a small amount from the ends, completing Umrah.',gu:'ઉમરાહની સઈ પછી પુરુષો મુંડન અથવા વાળ ટૂંકા કરે અને સ્ત્રીઓ વાળના છેડામાંથી થોડા વાળ કાપે; ત્યારબાદ ઉમરાહ પૂર્ણ થાય છે.'},tasks:{en:['Men: shave the head or shorten hair from all over the head.','Women: cut a small amount from the ends of the hair.','After this, the restrictions of Ihram end for Umrah.'],gu:['પુરુષો: માથું મુંડાવો અથવા સમગ્ર માથાના વાળ ટૂંકા કરો.','સ્ત્રીઓ: વાળના છેડામાંથી થોડા વાળ કાપે.','આ પછી ઉમરાહ માટે ઇહરામની પાબંદીઓ સમાપ્ત થાય છે.']},dua:['الْحَمْدُ لِلَّهِ','Alhamdulillah.','બધી પ્રશંસા અલ્લાહ માટે છે.'],pos:[18,1,4]}
};
export const daySets={
 '8 Dhul-Hijjah':['haram','mina'],
 '9 Dhul-Hijjah':['mina','arafah','muz'],
 '10 Dhul-Hijjah':['muz','jamarat','haramReturn','mina'],
 '11–13 Dhul-Hijjah':['mina','jamarat'],
 'Before departure':['farewell']
};