import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';

const Q=(s)=>document.querySelector(s), QA=(s)=>[...document.querySelectorAll(s)];
const UI={en:{hajj:'Sacred Sites Map',haram:'Masjid al-Haram Detail',reset:'Reset view',hint:'Drag to rotate • Scroll/pinch to zoom • Click a marker or landmark',selected:'SELECTED LOCATION',tasks:'What to do here',facts:'Location facts',dua:'Relevant dua / dhikr',focus:'◎ Focus in 3D',listen:'🔊 Listen',complete:'✓ Mark complete',completed:'✓ Completed',labels:'Labels',terrain:'Terrain',route:'Play journey route',pause:'Pause route',day:'Hajj day',distance:'Route distance',coords:'Coordinates',open:'Open guide',accuracy:'Coordinate-based sacred-sites layout',routeOverview:'Route overview',note:'Geographic positions use published coordinates where available. Landmark models are careful educational reconstructions, not survey-grade digital twins.',editorial:'Ritual text follows the uploaded guide structure and will continue to be checked page by page.'},gu:{hajj:'પવિત્ર સ્થળોનો નકશો',haram:'મસ્જિદુલ હરામની વિગત',reset:'દૃશ્ય રીસેટ કરો',hint:'ફેરવવા ખેંચો • ઝૂમ કરો • માર્કર અથવા સ્થળ પર ક્લિક કરો',selected:'પસંદ કરેલું સ્થળ',tasks:'અહીં શું કરવું',facts:'સ્થળની માહિતી',dua:'સંબંધિત દુઆ / ઝિક્ર',focus:'◎ 3D માં જુઓ',listen:'🔊 સાંભળો',complete:'✓ પૂર્ણ તરીકે નોંધો',completed:'✓ પૂર્ણ થયું',labels:'નામ',terrain:'ભૂપ્રદેશ',route:'સફરનો માર્ગ ચલાવો',pause:'માર્ગ થોભાવો',day:'હજનો દિવસ',distance:'માર્ગનું અંતર',coords:'સ્થાનાંક',open:'માર્ગદર્શન ખોલો',accuracy:'સ્થાનાંક આધારિત પવિત્ર સ્થળોની ગોઠવણી',routeOverview:'માર્ગનો સાર',note:'જ્યાં ઉપલબ્ધ છે ત્યાં પ્રકાશિત સ્થાનાંક પરથી સ્થળો ગોઠવ્યા છે. 3D મોડેલ કાળજીપૂર્વક બનાવેલ શૈક્ષણિક પુનર્નિર્માણ છે, સર્વે-ગ્રેડ ડિજિટલ નકલ નથી.',editorial:'ધાર્મિક લખાણ અપલોડ કરેલ પુસ્તકની રચનાને અનુસરે છે અને પૃષ્ઠવાર ચકાસણી ચાલુ રહેશે.'}};
const P={haram:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Edited_Great_Mosque_of_Mecca1_5-2019-ccsa4.0_%28cropped%29.jpg/1000px-Edited_Great_Mosque_of_Mecca1_5-2019-ccsa4.0_%28cropped%29.jpg',kaaba:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/The_Ka%27ba%2C_Great_Mosque_of_Mecca%2C_Saudi_Arabia_%284%29.jpg/900px-The_Ka%27ba%2C_Great_Mosque_of_Mecca%2C_Saudi_Arabia_%284%29.jpg',mina:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Mina_Overview.JPG/1000px-Mina_Overview.JPG',arafah:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Pilgrims_cover_Arafat%27s_roads%2C_plains_and_mountain_-_Flickr_-_Al_Jazeera_English.jpg/1000px-Pilgrims_cover_Arafat%27s_roads%2C_plains_and_mountain_-_Flickr_-_Al_Jazeera_English.jpg',muz:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Fajr_in_Muzdalifah.jpg/900px-Fajr_in_Muzdalifah.jpg',jamarat:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Jamaraat_Bridge_2.jpg/1000px-Jamaraat_Bridge_2.jpg',safa:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Mount_Safa_Mecca.jpg/800px-Mount_Safa_Mecca.jpg',marwah:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Al-Marwah_2.JPG/800px-Al-Marwah_2.JPG'};
const tal=['لَبَّيْكَ اللَّهُمَّ لَبَّيْكَ','Labbayk Allahumma labbayk.','હે અલ્લાહ! હું હાજર છું.'];
const duaA=['لَا إِلٰهَ إِلَّا اللّٰهُ وَحْدَهُ لَا شَرِيكَ لَهُ','La ilaha illallahu wahdahu la sharika lah.','અલ્લાહ સિવાય કોઈ સાચો ઉપાસ્ય નથી; તે એકલો છે.'];
const DATA={
 hajj:{
  haram:{n:['Masjid al-Haram & Kaaba','મસ્જિદુલ હરામ અને કાબા'],a:'المسجد الحرام والكعبة',c:[21.4225,39.82617],day:'8 Dhul-Hijjah',d:['Starting point','શરૂઆતનું સ્થળ'],i:['Begin the Hajj journey in Makkah. The 3D city model now includes the Haram enclosure, Kaaba, minarets and a simplified Abraj Al-Bait skyline.','હજની સફર મક્કાથી શરૂ કરો. સુધારેલ 3D દૃશ્યમાં હરમ, કાબા, મિનારા અને અબરાજ અલ-બૈતનું સરળ સ્વરૂપ છે.'],t:[['Enter Ihram for Hajj according to the guide.','Make the intention and recite Talbiyah.','Leave for Mina with your group.'],['પુસ્તક મુજબ હજનો ઇહરામ બાંધો.','નિયત કરો અને તલ્બિયહ પઢો.','જૂથ સાથે મીના તરફ જાઓ.']],f:[['Coordinate anchor: 21.42250° N, 39.82617° E','Kaaba proportions use published dimensions.','Local buildings are orientation models, not exact current construction.'],['સ્થાનાંક: 21.42250° N, 39.82617° E','કાબાનું અનુપાત પ્રકાશિત માપ પરથી છે.','આસપાસની ઇમારતો દિશા સમજવા માટે છે, વર્તમાન બાંધકામની ચોક્કસ નકલ નથી.']],dua:tal,p:[P.haram,P.kaaba]},
  mina:{n:['Mina Tent Valley','મીનાની તંબુવાળી ખીણ'],a:'مِنَى',c:[21.41527,39.8778],day:'8 Dhul-Hijjah',d:['Approx. 7–8 km from the Haram','હરમથી અંદાજે 7–8 કિમી'],i:['Mina is modelled as a long valley with dense tent sectors, service roads, Masjid al-Khayf and the Jamarat end of the valley.','મીનાને લાંબી ખીણ તરીકે દર્શાવ્યું છે જેમાં તંબુ ક્ષેત્રો, સેવા માર્ગો, મસ્જિદ અલ-ખૈફ અને જમરાત છે.'],t:[['Go to Mina while reciting Talbiyah.','Pray according to the method in the uploaded guide.','Spend the night and leave for Arafah after sunrise.'],['તલ્બિયહ પઢતા મીના જાઓ.','અપલોડ કરેલ પુસ્તક મુજબ નમાઝ અદા કરો.','રાત રોકાઈ સૂર્યોદય પછી અરફાત જાઓ.']],f:[['The anchor uses published coordinates of Masjid al-Khayf.','Tent rows follow the valley direction.','Jamarat is shown separately at the western end.'],['આધાર મસ્જિદ અલ-ખૈફના પ્રકાશિત સ્થાનાંક પરથી છે.','તંબુની પંક્તિઓ ખીણની દિશામાં છે.','પશ્ચિમ છેડે જમરાત અલગ બતાવ્યું છે.']],dua:tal,p:[P.mina]},
  arafah:{n:['Arafah & Jabal al-Rahmah','અરફાત અને જબલુર રહમહ'],a:'عَرَفَات وَجَبَل الرَّحْمَة',c:[21.35472,39.98389],day:'9 Dhul-Hijjah',d:['Approx. 14 km from Mina','મીનાથી અંદાજે 14 કિમી'],i:['The scene shows the broad Arafah plain, its boundary, Jabal al-Rahmah as a rocky hill and Masjid Namirah on the western side.','દૃશ્યમાં અરફાતનું વિશાળ મેદાન, તેની હદ, પથ્થરી જબલુર રહમહ અને પશ્ચિમ તરફ મસ્જિદ નિમરાહ છે.'],t:[['Remain inside Arafah during the required time.','Make abundant sincere dua, repentance and dhikr.','Do not leave before sunset.'],['જરૂરી સમય અરફાતની હદમાં રહો.','ઘણી દિલથી દુઆ, તૌબા અને ઝિક્ર કરો.','સૂર્યાસ્ત પહેલાં ન નીકળો.']],f:[['Jabal al-Rahmah anchor: 21.35472° N, 39.98389° E','The hill is visually distinct but the entire Arafah boundary matters.','Masjid Namirah is included as an orientation landmark.'],['જબલુર રહમહ સ્થાનાંક: 21.35472° N, 39.98389° E','માત્ર ટેકરી નહીં, અરફાતની આખી હદ મહત્વની છે.','દિશા માટે મસ્જિદ નિમરાહ પણ દર્શાવેલ છે.']],dua:duaA,p:[P.arafah]},
  muz:{n:['Muzdalifah & al-Mash‘ar al-Haram','મુઝદલિફા અને મશઅરુલ હરામ'],a:'مُزْدَلِفَة وَالْمَشْعَر الحَرَام',c:[21.3893,39.9127],day:'Night of 9th',d:['Approx. 9 km from Arafah','અરફાતથી અંદાજે 9 કિમી'],i:['Muzdalifah is shown as an open night plain with roads, lighting and a simplified al-Mash‘ar al-Haram mosque.','મુઝદલિફાને ખુલ્લા રાત્રિના મેદાન, માર્ગો, લાઇટો અને સરળ મશઅરુલ હરામ મસ્જિદ સાથે બતાવ્યું છે.'],t:[['Leave Arafah after sunset.','Pray and stay according to the guide.','Remember Allah and prepare small pebbles without crowding.'],['સૂર્યાસ્ત પછી અરફાત છોડો.','પુસ્તક મુજબ નમાઝ અને રોકાણ કરો.','અલ્લાહનો ઝિક્ર કરો અને ભીડ વગર નાની કાંકરીઓ તૈયાર કરો.']],f:[['The anchor is approximate because the ritual area is broad.','Night lighting helps distinguish this stage.','The route proceeds westward back toward Mina.'],['વિસ્તાર મોટો હોવાથી આધાર અંદાજિત છે.','રાત્રિ લાઇટિંગ આ તબક્કાને અલગ બતાવે છે.','માર્ગ પશ્ચિમ તરફ પાછો મીના જાય છે.']],dua:['فَاذْكُرُوا اللَّهَ عِنْدَ الْمَشْعَرِ الْحَرَامِ','Remember Allah at al-Mash‘ar al-Haram.','મશઅરુલ હરામ પાસે અલ્લાહનો ઝિક્ર કરો.'],p:[P.muz]},
  jamarat:{n:['Jamarat Complex','જમરાત કોમ્પ્લેક્સ'],a:'جِسْر الجَمَرَات',c:[21.42139,39.87278],day:'10–13 Dhul-Hijjah',d:['At the western end of Mina','મીનાના પશ્ચિમ છેડે'],i:['The improved model has a multi-level bridge, approach ramps and three elongated Jamrah walls in their relative sequence.','સુધારેલ મોડેલમાં બહુસ્તરીય બ્રિજ, રેમ્પ અને ક્રમ મુજબ ત્રણ લાંબી જમરાહ દિવાલો છે.'],t:[['Follow the day-specific stoning order in the guide.','Use seven pebbles for each required Jamrah.','Say Allahu Akbar with each throw and never push or harm others.'],['પુસ્તકમાં આપેલ દિવસ મુજબનો ક્રમ અનુસરો.','દરેક જરૂરી જમરાહ માટે સાત કાંકરી વાપરો.','દરેક ફેંક સાથે અલ્લાહુ અકબર કહો અને ધક્કામુક્કી ન કરો.']],f:[['Coordinate anchor: 21.42139° N, 39.87278° E','The first-to-middle and middle-to-large spacing is represented proportionally.','The walls are enlarged slightly for clear selection.'],['સ્થાનાંક: 21.42139° N, 39.87278° E','ત્રણ જમરાહ વચ્ચેનું અંતર અનુપાતમાં દર્શાવ્યું છે.','પસંદ કરી શકાય તે માટે દિવાલો થોડાં મોટા દર્શાવ્યા છે.']],dua:['اللّٰهُ أَكْبَرُ','Allahu Akbar.','અલ્લાહ સૌથી મહાન છે.'],p:[P.jamarat]}
 },
 haram:{
  kaaba:{n:['The Kaaba','કાબા'],a:'الكَعْبَة المُشَرَّفَة',day:'Tawaf',d:['Centre of the Mataf','મતાફનું કેન્દ્ર'],i:['The detailed model uses the published rectangular proportions, a raised Kiswah band, door, corner markers and a visible Tawaf path.','વિગતવાર મોડેલમાં પ્રકાશિત અનુપાત, કિસ્વાની પટ્ટી, દરવાજો, ખૂણાના નિશાન અને તવાફનો માર્ગ છે.'],t:[['Begin Tawaf at Hajar al-Aswad.','Keep the Kaaba on your left and complete seven anti-clockwise circuits.','Do not push or harm anyone.'],['હજરે અસ્વદથી તવાફ શરૂ કરો.','કાબાને ડાબી બાજુ રાખી ઘડિયાળની વિરુદ્ધ સાત ચક્કર કરો.','ધક્કામુક્કી કે નુકસાન ન કરો.']],f:[['Model ratio is based on published dimensions: about 12.86 m × 11.03 m × 13.1 m.','The Tawaf rings are educational guides and do not prescribe a fixed walking radius.'],['મોડેલનું અનુપાત પ્રકાશિત માપ આશરે 12.86 × 11.03 × 13.1 મીટર પરથી છે.','તવાફના વલયો શૈક્ષણિક છે; તેઓ ચોક્કસ ચાલવાની ત્રિજ્યા નક્કી કરતા નથી.']],dua:['بِسْمِ اللّٰهِ، اللّٰهُ أَكْبَرُ','Bismillah, Allahu Akbar.','અલ્લાહના નામથી, અલ્લાહ સૌથી મહાન છે.'],p:[P.kaaba]},
  blackstone:{n:['Hajar al-Aswad','હજરે અસ્વદ'],a:'الحَجَر الأَسْوَد',day:'Tawaf start',d:['Eastern corner of the Kaaba','કાબાનો પૂર્વીય ખૂણો'],i:['A selectable silver-framed dark inset marks the Tawaf start alignment.','ચાંદીની ફ્રેમવાળો કાળો ભાગ તવાફની શરૂઆતની રેખા દર્શાવે છે.'],t:[['Align here to begin each circuit.','Follow the guide if access is safe.','Otherwise gesture from a distance and continue without pushing.'],['દરેક ચક્કર અહીંથી શરૂ કરો.','સુરક્ષિત રીતે પહોંચાય તો પુસ્તક મુજબ અમલ કરો.','નહીં તો દૂરથી ઇશારો કરી ધક્કા વગર આગળ વધો.']],f:[['The visual marker is enlarged for selection.'],['પસંદ કરી શકાય તે માટે દૃશ્ય મોટું કરેલ છે.']],dua:['بِسْمِ اللّٰهِ، اللّٰهُ أَكْبَرُ','Bismillah, Allahu Akbar.','અલ્લાહના નામથી, અલ્લાહ સૌથી મહાન છે.'],p:[P.kaaba]},
  hijr:{n:['Hijr Ismail / Hatim','હિજ્રે ઇસ્માઈલ / હતીમ'],a:'حِجْر إِسْمَاعِيل',day:'Tawaf landmark',d:['North-west side of the Kaaba','કાબાની ઉત્તર-પશ્ચિમ બાજુ'],i:['The low semicircular wall and its open ends are reconstructed beside the Kaaba.','કાબાની બાજુ નીચી અર્ધવર્તુળ દિવાલ અને તેના ખુલ્લા છેડા દર્શાવ્યા છે.'],t:[['Tawaf must pass outside the Hijr.','Respect crowd-control access.'],['તવાફ હિજ્રની બહારથી કરો.','ભીડ નિયંત્રણ મુજબ પ્રવેશ કરો.']],f:[['The curved wall is separately clickable.'],['વક્ર દિવાલ અલગથી ક્લિક કરી શકાય છે.']],dua:['','',''],p:[P.kaaba]},
  maqam:{n:['Maqam Ibrahim','મકામે ઇબ્રાહીમ'],a:'مَقَام إِبْرَاهِيم',day:'After Tawaf',d:['East of the Kaaba in the Mataf','મતાફમાં કાબાની પૂર્વ બાજુ'],i:['The scene includes a golden inner enclosure and transparent outer casing.','દૃશ્યમાં સોનેરી અંદરનું આવરણ અને પારદર્શક બહારનું કવચ છે.'],t:[['After Tawaf, pray two rak‘ah in a suitable place according to the guide.','Do not block circulation when crowded.'],['તવાફ પછી પુસ્તક મુજબ યોગ્ય જગ્યાએ બે રકઅત પઢો.','ભીડમાં આવનજાવન રોકશો નહીં.']],f:[['Coordinate anchor: 21.42262° N, 39.82633° E.'],['સ્થાનાંક: 21.42262° N, 39.82633° E.']],dua:['','',''],p:[P.kaaba]},
  safa:{n:['Safa','સફા'],a:'الصَّفَا',day:'Sa‘i begins',d:['Start of the Mas‘a corridor','મસઆ માર્ગની શરૂઆત'],i:['The model shows Safa rock inside a roofed Mas‘a corridor with lanes and green-light markers.','મોડેલ છતવાળા મસઆ માર્ગમાં સફાના પથ્થરો, ચાલવાના માર્ગ અને લીલા નિશાન બતાવે છે.'],t:[['Begin Sa‘i at Safa.','Face the Kaaba direction and make the prescribed remembrance and personal dua.','Proceed toward Marwah.'],['સફાથી સઈ શરૂ કરો.','કાબાની દિશામાં થઈ સંબંધિત ઝિક્ર અને વ્યક્તિગત દુઆ કરો.','મરવા તરફ આગળ વધો.']],f:[['Coordinate anchor: 21.42361° N, 39.82722° E.','The displayed corridor is compressed but the distance label is preserved.'],['સ્થાનાંક: 21.42361° N, 39.82722° E.','મોડેલ માર્ગ સંકોચાયેલ છે પરંતુ અંતરનું લેબલ રાખ્યું છે.']],dua:['إِنَّ الصَّفَا وَالْمَرْوَةَ مِنْ شَعَائِرِ اللَّهِ','Indeed, Safa and Marwah are among the symbols of Allah.','નિશ્ચિત રીતે સફા અને મરવા અલ્લાહની નિશાનીઓમાંથી છે.'],p:[P.safa]},
  marwah:{n:['Marwah','મરવા'],a:'المَرْوَة',day:'Sa‘i endpoint',d:['About 450 m from Safa','સફાથી આશરે 450 મીટર'],i:['Marwah is the opposite endpoint; the seventh one-way lap ends here.','મરવા સામેનો અંતિમ બિંદુ છે; સાતમો એક-તરફી ચક્કર અહીં પૂર્ણ થાય છે.'],t:[['Count each one-way journey correctly.','Complete the seventh lap at Marwah.','Make dhikr and dua without blocking others.'],['દરેક એક-તરફી સફર સાચી રીતે ગણો.','સાતમો ચક્કર મરવા પર પૂર્ણ કરો.','માર્ગ રોક્યા વગર ઝિક્ર અને દુઆ કરો.']],f:[['The corridor has walking lanes, a central mobility lane and green-light markers.'],['માર્ગમાં ચાલવાના માર્ગ, મધ્ય ગતિશીલતા માર્ગ અને લીલા નિશાન છે.']],dua:['','',''],p:[P.marwah]}
 }
};

let lang='en',mode='hajj',selected='haram',scene,camera,renderer,controls,root,raycaster,mouse,routeCurve,traveller,playing=false,rt=0,labelsOn=true,terrainOn=true,photos=[],photoIndex=0;
const clickable=[],labels=[],pos={};const done=JSON.parse(localStorage.getItem('huDone')||'{}');
const mat=(c)=>new THREE.MeshStandardMaterial({color:c,roughness:.75,metalness:.04});
const box=(x,y,z,c)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(x,y,z),mat(c));m.castShadow=m.receiveShadow=true;return m};
const cyl=(r1,r2,h,c,s=20)=>{const m=new THREE.Mesh(new THREE.CylinderGeometry(r1,r2,h,s),mat(c));m.castShadow=m.receiveShadow=true;return m};
const sph=(r,c)=>{const m=new THREE.Mesh(new THREE.SphereGeometry(r,18,12),mat(c));m.castShadow=true;return m};
function project(lat,lon){const k=2.2,lat0=21.4,lon0=39.9;return new THREE.Vector3((lon-lon0)*103.5*Math.cos(lat0*Math.PI/180)*k,0,-(lat-lat0)*111*k)}
function label(text,key,p){const c=document.createElement('canvas'),x=c.getContext('2d');c.width=520;c.height=110;x.fillStyle='rgba(5,47,40,.9)';x.roundRect(5,5,510,100,20);x.fill();x.strokeStyle='#d8b25a';x.lineWidth=4;x.stroke();x.fillStyle='white';x.font='700 28px Arial';x.textAlign='center';x.textBaseline='middle';x.fillText(text,260,55);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,depthTest:false}));s.position.copy(p).add(new THREE.Vector3(0,2.5,0));s.scale.set(8,1.7,1);s.userData={key};root.add(s);labels.push(s);clickable.push(s)}
function marker(key,p,text){const g=new THREE.Group();g.position.copy(p);const ring=new THREE.Mesh(new THREE.TorusGeometry(.75,.08,10,36),new THREE.MeshBasicMaterial({color:0xd8b25a}));ring.rotation.x=Math.PI/2;ring.position.y=.08;const orb=sph(.32,0xffdf83);orb.position.y=.75;orb.material.emissive=new THREE.Color(0x6c4c0e);orb.material.emissiveIntensity=.8;orb.userData={key};clickable.push(orb);g.add(ring,orb);root.add(g);label(text,key,p);pos[key]=p.clone()}
function keyify(o,key){o.traverse?.(m=>{if(m.isMesh){m.userData.key=key;clickable.push(m)}})}
function terrain(){const g=new THREE.Mesh(new THREE.PlaneGeometry(120,90,45,35),mat(0xa89368));g.rotation.x=-Math.PI/2;const a=g.geometry.attributes.position;for(let i=0;i<a.count;i++){const x=a.getX(i),y=a.getY(i),edge=Math.max(0,(Math.abs(x)-35)/18)+Math.max(0,(Math.abs(y)-24)/13);a.setZ(i,Math.max(0,edge)*3+Math.sin(x*.22)*Math.cos(y*.19)*.35)}g.geometry.computeVertexNormals();g.receiveShadow=true;root.add(g);g.userData.terrain=true;for(let i=0;i<80;i++){const r=cyl(.4+Math.random()*1.1,.1,1+Math.random()*3,0x7c684c,7);r.position.set((Math.random()-.5)*105,r.geometry.parameters.height/2,(Math.random()-.5)*74);r.scale.y=.35;root.add(r);r.userData.terrain=true}}
function kaaba(p,s=1,key='haram'){const g=new THREE.Group();g.position.copy(p);g.scale.setScalar(s);const k=box(5.5,6.55,4.72,0x121212);k.position.y=3.28;const band=box(5.62,.72,4.84,0xd0a13c);band.position.y=4.95;const door=box(1.25,2.6,.14,0xd9ad4b);door.position.set(1.15,2,2.43);g.add(k,band,door);root.add(g);keyify(g,key);return g}
function city(p){const pad=cyl(10,10,.25,0xe7e1d3,64);pad.position.copy(p);pad.position.y=.12;root.add(pad);kaaba(p.clone().add(new THREE.Vector3(0,.25,0)),.55,'haram');for(let i=0;i<30;i++){const a=i/30*Math.PI*2,r=7.3,b=box(.7,1.4,.7,0xe8e1d2);b.position.set(p.x+Math.cos(a)*r,.7,p.z+Math.sin(a)*r);root.add(b)}for(let i=0;i<6;i++){const a=i/6*Math.PI*2,m=cyl(.17,.28,4.8,0xe8dfce,12);m.position.set(p.x+Math.cos(a)*8.6,2.4,p.z+Math.sin(a)*8.6);root.add(m)}const tower=box(2.6,12,2.6,0xb8af9f);tower.position.set(p.x-7,6,p.z-8);root.add(tower);keyify(pad,'haram')}
function tents(p){const base=cyl(8.5,8.5,.18,0xcab68d,64);base.position.copy(p);root.add(base);for(let x=-7;x<=7;x+=1.45)for(let z=-5;z<=5;z+=1.45){const t=cyl(.62,0,1.15,0xf3f0e7,12);t.position.set(p.x+x,.58,p.z+z);root.add(t)}for(let z=-5;z<=5;z+=3){const road=box(17,.08,.35,0x6e6d68);road.position.set(p.x,.12,p.z+z);root.add(road)}const mosque=box(4,.65,2.5,0xe8e3d7);mosque.position.set(p.x+1,.38,p.z-6.3);root.add(mosque);for(let x=-1.4;x<=1.4;x+=.7){const d=cyl(.33,.33,.35,0xe8e3d7,18);d.position.set(p.x+1+x,.85,p.z-6.3);root.add(d)}keyify(base,'mina')}
function arafah(p){const base=cyl(10.5,10.5,.14,0xcbb17b,64);base.position.copy(p);root.add(base);const hill=cyl(4.4,1.1,4.2,0x8c7150,9);hill.position.set(p.x+3,2.1,p.z-1.5);hill.scale.z=.65;root.add(hill);const pillar=cyl(.13,.16,3.2,0xf7f7f3,12);pillar.position.set(p.x+3,5.3,p.z-1.5);root.add(pillar);const mosque=box(7,.55,2.8,0xe8e1d3);mosque.position.set(p.x-5,.35,p.z+5.5);root.add(mosque);for(let i=0;i<9;i++){const d=cyl(.32,.32,.34,0xe8e1d3,18);d.position.set(p.x-8+i*.75,.8,p.z+5.5);root.add(d)}keyify(base,'arafah');keyify(hill,'arafah')}
function muz(p){const base=cyl(8,8,.13,0x87775c,64);base.position.copy(p);root.add(base);for(let i=0;i<24;i++){const pole=cyl(.05,.05,1.8,0x555555,8);pole.position.set(p.x+(Math.random()-.5)*13,.9,p.z+(Math.random()-.5)*10);root.add(pole);const light=new THREE.PointLight(0xffd27c,.35,4);light.position.copy(pole.position).add(new THREE.Vector3(0,1,0));root.add(light)}const m=box(4,.55,2.2,0xf0eee5);m.position.set(p.x+1,.34,p.z-2);root.add(m);const dome=cyl(.75,.75,.3,0xf0eee5,24);dome.position.set(p.x+1,.78,p.z-2);root.add(dome);keyify(base,'muz')}
function jamarat(p){const g=new THREE.Group();g.position.copy(p);for(let l=0;l<3;l++){const deck=box(10,.35,3.2,0xb9bbb8);deck.position.y=.7+l*1.05;g.add(deck)}for(let i=0;i<4;i++){const col=box(.45,4,.55,0xd8d8d4);col.position.set(-3.6+i*2.4,2,0);g.add(col)}[-2.8,-.3,3].forEach((x,i)=>{const wall=box(.35,2.2,i===2?2.8:2.1,0xeee9dd);wall.position.set(x,2.1,0);g.add(wall)});const ramp=box(7,.25,1.4,0xb9bbb8);ramp.rotation.z=-.2;ramp.position.set(-7,1,0);g.add(ramp);root.add(g);keyify(g,'jamarat')}
function tube(points,color=0xd8b25a){routeCurve=new THREE.CatmullRomCurve3(points,false,'centripetal');const m=new THREE.Mesh(new THREE.TubeGeometry(routeCurve,200,.12,8,false),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.95}));m.position.y=.18;root.add(m);traveller=sph(.35,0xffffff);traveller.material.emissive=new THREE.Color(0x1aa87f);traveller.material.emissiveIntensity=1.4;root.add(traveller)}
function buildHajj(){terrain();const ph=project(21.4225,39.82617),pm=project(21.41527,39.8778),pj=project(21.42139,39.87278),pa=project(21.35472,39.98389),pz=project(21.3893,39.9127);city(ph);tents(pm);arafah(pa);muz(pz);jamarat(pj);const route=[ph,pm,pa,pz,pj,ph].map(v=>v.clone().setY(.4));tube(route);[['haram',ph],['mina',pm],['arafah',pa],['muz',pz],['jamarat',pj]].forEach(([k,p])=>marker(k,p,DATA.hajj[k].n[lang]));Q('#scaleLabel').textContent='5 km'}
function rockCluster(p,key){for(let i=0;i<10;i++){const r=new THREE.Mesh(new THREE.DodecahedronGeometry(.55+Math.random()*.5,0),mat(0x8b7659));r.position.set(p.x+(Math.random()-.5)*2.7,.45+Math.random()*.35,p.z+(Math.random()-.5)*1.6);r.scale.y=.5;root.add(r);keyify(r,key)}}
function buildHaram(){const marble=new THREE.Mesh(new THREE.CircleGeometry(28,96),mat(0xf0eee7));marble.rotation.x=-Math.PI/2;marble.receiveShadow=true;root.add(marble);kaaba(new THREE.Vector3(0,.05,0),1,'kaaba');const stone=sph(.32,0x151515);stone.position.set(2.82,1.45,2.42);stone.userData.key='blackstone';root.add(stone);clickable.push(stone);const hijr=new THREE.Mesh(new THREE.TorusGeometry(4.2,.18,12,45,Math.PI),mat(0xeee8d8));hijr.rotation.x=Math.PI/2;hijr.rotation.z=Math.PI;hijr.position.set(0,.38,-3.1);root.add(hijr);keyify(hijr,'hijr');const maq=cyl(.65,.65,2.4,0xd2a43c,24);maq.position.set(0,1.2,6);root.add(maq);const glass=new THREE.Mesh(new THREE.CylinderGeometry(1,1,3,28),new THREE.MeshPhysicalMaterial({color:0xffffff,transparent:true,opacity:.24,transmission:.75,roughness:.08}));glass.position.set(0,1.5,6);root.add(glass);keyify(glass,'maqam');for(let r=7;r<15;r+=2){const ring=new THREE.Mesh(new THREE.TorusGeometry(r,.035,6,100),new THREE.MeshBasicMaterial({color:0xd8b25a,transparent:true,opacity:.4}));ring.rotation.x=Math.PI/2;ring.position.y=.08;root.add(ring)}const corridor=box(35,.18,6.5,0xdedbd2);corridor.position.set(0,.12,-15);root.add(corridor);for(let x=-17;x<=17;x+=2){const c1=cyl(.12,.12,3.4,0xe7e3d9,10);c1.position.set(x,1.7,-18);const c2=c1.clone();c2.position.z=-12;root.add(c1,c2)}const roof=box(35,.18,6.5,0xe8e5dc);roof.position.set(0,3.45,-15);root.add(roof);[-4,4].forEach(x=>{const green=box(.2,3,6.2,0x32b276);green.position.set(x,1.6,-15);root.add(green)});rockCluster(new THREE.Vector3(-17,0,-15),'safa');rockCluster(new THREE.Vector3(17,0,-15),'marwah');tube([new THREE.Vector3(-16,.4,-15),new THREE.Vector3(16,.4,-15),new THREE.Vector3(-16,.4,-15)],0x39a878);[['kaaba',new THREE.Vector3(0,0,0)],['blackstone',new THREE.Vector3(3,0,2.5)],['hijr',new THREE.Vector3(0,0,-5)],['maqam',new THREE.Vector3(0,0,6)],['safa',new THREE.Vector3(-17,0,-15)],['marwah',new THREE.Vector3(17,0,-15)]].forEach(([k,p])=>marker(k,p,DATA.haram[k].n[lang]));for(let i=0;i<22;i++){const pilgrim=sph(.12,0xffffff);pilgrim.userData.t=i/22;root.add(pilgrim);pilgrim.userData.pilgrim=true}Q('#scaleLabel').textContent='50 m'}
function resetGroups(){if(root)scene.remove(root);root=new THREE.Group();scene.add(root);clickable.length=0;labels.length=0;Object.keys(pos).forEach(k=>delete pos[k]);routeCurve=traveller=null;rt=0;Q('#routeSlider').value=0}
function build(){resetGroups();mode==='hajj'?buildHajj():buildHaram();renderLegend();renderRoute();select(mode==='hajj'?'haram':'kaaba',false);resetView()}
function renderLegend(){const data=DATA[mode];Q('#legend').innerHTML=Object.entries(data).map(([k,v])=>`<button data-k="${k}">${v.n[lang]}</button>`).join('');QA('#legend button').forEach(b=>b.onclick=()=>select(b.dataset.k))}
function renderRoute(){const keys=mode==='hajj'?['haram','mina','arafah','muz','jamarat']:['kaaba','blackstone','hijr','maqam','safa','marwah'];Q('#routeSteps').innerHTML=keys.map(k=>`<button data-k="${k}">${DATA[mode][k].n[lang]}</button>`).join('');QA('#routeSteps button').forEach(b=>b.onclick=()=>select(b.dataset.k));Q('#routeTotal').textContent=mode==='hajj'?'≈ 44 km route overview':'Tawaf + Sa‘i learning route'}
function select(k,focus=true){if(!DATA[mode][k])return;selected=k;const d=DATA[mode][k],u=UI[lang];Q('#placeTitle').textContent=d.n[lang];Q('#placeArabic').textContent=d.a;Q('#placeIntro').textContent=d.i[lang];Q('#dayValue').textContent=d.day;Q('#distanceValue').textContent=d.d[lang];Q('#coordinatesValue').textContent=d.c?`${d.c[0].toFixed(5)}° N, ${d.c[1].toFixed(5)}° E`:'Local Haram landmark';Q('#qualityBadge').textContent=d.c?'Coordinate-based':'Educational model';Q('#qualityBadge').classList.toggle('approx',!d.c);Q('#taskList').innerHTML=d.t[lang].map((x,i)=>`<div class="task"><i>${i+1}</i><span>${x}</span></div>`).join('');Q('#factList').innerHTML=d.f[lang].map(x=>`<div class="fact">${x}</div>`).join('');Q('#duaArabic').textContent=d.dua[0];Q('#duaTrans').textContent=d.dua[1];Q('#duaMeaning').textContent=d.dua[2];Q('#duaSection').style.display=d.dua[0]?'block':'none';photos=d.p||[P.haram];photoIndex=0;showPhoto();Q('#completeBtn').textContent=done[mode+':'+k]?u.completed:u.complete;Q('#completeBtn').classList.toggle('done',!!done[mode+':'+k]);QA('#legend button,#routeSteps button').forEach(b=>b.classList.toggle('active',b.dataset.k===k));if(focus)focusOn(k);if(innerWidth<821)Q('#infoPanel').classList.add('open')}
function showPhoto(){Q('#photo').src=photos[photoIndex];Q('#photoCredit').textContent='Photo: Wikimedia Commons';Q('#photoCredit').href='https://commons.wikimedia.org/';Q('#photoDots').innerHTML=photos.map((_,i)=>`<i class="${i===photoIndex?'active':''}"></i>`).join('');Q('#photoPrev').style.display=Q('#photoNext').style.display=photos.length>1?'block':'none'}
function focusOn(k){const p=pos[k]||new THREE.Vector3();controls.target.copy(p);camera.position.copy(p).add(mode==='hajj'?new THREE.Vector3(10,10,14):new THREE.Vector3(8,7,10))}
function resetView(){if(mode==='hajj'){camera.position.set(18,38,52);controls.target.set(0,0,0)}else{camera.position.set(30,30,37);controls.target.set(0,0,-5)}controls.update()}
function setUI(){const u=UI[lang];Q('#hajjTab').textContent=u.hajj;Q('#haramTab').textContent=u.haram;Q('#resetText').textContent=u.reset;Q('#sceneHint').textContent=u.hint;Q('#selectedText').textContent=u.selected;Q('#tasksTitle').textContent=u.tasks;Q('#factsTitle').textContent=u.facts;Q('#duaTitle').textContent=u.dua;Q('#focusBtn').textContent=u.focus;Q('#listenBtn').textContent=u.listen;Q('#labelsText').textContent=u.labels;Q('#terrainText').textContent=u.terrain;Q('#routeText').textContent=playing?u.pause:u.route;Q('#dayLabel').textContent=u.day;Q('#distanceLabel').textContent=u.distance;Q('#coordinatesLabel').textContent=u.coords;Q('#mobilePanelBtn').textContent=u.open;Q('#accuracyText').textContent=u.accuracy;Q('#routeOverviewTitle').textContent=u.routeOverview;Q('#scaleNote').textContent=u.note;Q('#editorialNote').textContent=u.editorial;Q('#langBtn').textContent=lang==='en'?'ગુજરાતી':'English';QA('#modeTabs button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode))}
function init(){scene=new THREE.Scene();scene.background=new THREE.Color(0x9db0a8);scene.fog=new THREE.FogExp2(0x9db0a8,.007);camera=new THREE.PerspectiveCamera(45,1,.1,400);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;Q('#scene').append(renderer.domElement);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxPolarAngle=Math.PI*.48;controls.minDistance=5;controls.maxDistance=115;raycaster=new THREE.Raycaster();mouse=new THREE.Vector2();scene.add(new THREE.HemisphereLight(0xfff5dc,0x485c51,2.4));const sun=new THREE.DirectionalLight(0xfff0cb,3.2);sun.position.set(-30,55,25);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);addEvents();setUI();build();resize();requestAnimationFrame(loop);setTimeout(()=>Q('#loading').classList.add('hide'),500)}
function resize(){const el=Q('#scene'),w=el.clientWidth,h=el.clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)}
function addEvents(){addEventListener('resize',resize);renderer.domElement.addEventListener('pointerup',e=>{const r=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height)*2+1);raycaster.setFromCamera(mouse,camera);const hit=raycaster.intersectObjects(clickable,true).find(x=>x.object.userData.key);if(hit)select(hit.object.userData.key)});QA('#modeTabs button').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;playing=false;setUI();build()});Q('#langBtn').onclick=()=>{lang=lang==='en'?'gu':'en';setUI();build()};Q('#resetBtn').onclick=resetView;Q('#focusBtn').onclick=()=>focusOn(selected);Q('#listenBtn').onclick=()=>{const d=DATA[mode][selected];speechSynthesis.cancel();const x=new SpeechSynthesisUtterance(`${d.n[lang]}. ${d.i[lang]}. ${d.t[lang].join('. ')}`);x.lang=lang==='gu'?'gu-IN':'en-US';speechSynthesis.speak(x)};Q('#completeBtn').onclick=()=>{done[mode+':'+selected]=!done[mode+':'+selected];localStorage.setItem('huDone',JSON.stringify(done));select(selected,false)};Q('#labelsBtn').onclick=()=>{labelsOn=!labelsOn;labels.forEach(x=>x.visible=labelsOn);Q('#labelsBtn').classList.toggle('active',labelsOn)};Q('#terrainBtn').onclick=()=>{terrainOn=!terrainOn;root.traverse(x=>{if(x.userData.terrain)x.visible=terrainOn});Q('#terrainBtn').classList.toggle('active',terrainOn)};Q('#routeBtn').onclick=()=>{playing=!playing;setUI()};Q('#routeSlider').oninput=e=>{rt=+e.target.value/1000;playing=false;setUI()};Q('#photoPrev').onclick=()=>{photoIndex=(photoIndex-1+photos.length)%photos.length;showPhoto()};Q('#photoNext').onclick=()=>{photoIndex=(photoIndex+1)%photos.length;showPhoto()};Q('#mobilePanelBtn').onclick=()=>Q('#infoPanel').classList.add('open');Q('#closePanel').onclick=()=>Q('#infoPanel').classList.remove('open')}
function loop(t){requestAnimationFrame(loop);controls.update();if(playing&&routeCurve){rt=(rt+.00065)%1;Q('#routeSlider').value=Math.round(rt*1000)}if(routeCurve&&traveller){const p=routeCurve.getPoint(rt);traveller.position.copy(p).add(new THREE.Vector3(0,.85,0))}if(mode==='haram'){root.traverse(o=>{if(o.userData.pilgrim){const a=(t*.00015+o.userData.t)*Math.PI*2,r=8+(o.userData.t%3)*1.7;o.position.set(Math.cos(a)*r,.2,Math.sin(a)*r)}})}renderer.render(scene,camera)}
init();
