import { Download, RotateCcw, Settings2, Upload } from 'lucide-react';
import { useRef, useState } from 'react';
import { useApp } from '../components/AppContext';
import type { AppState } from '../types';

export function ToolsPage(){
  const {state,replaceState,reset,setFontScale,setAudioRate}=useApp(); const l=state.language; const input=useRef<HTMLInputElement>(null); const [message,setMessage]=useState('');
  const exportData=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='manasik-3d-backup.json';a.click();URL.revokeObjectURL(url);};
  const importData=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>{try{replaceState(JSON.parse(String(reader.result)) as AppState);setMessage(l==='en'?'Backup imported successfully.':'બેકઅપ સફળતાપૂર્વક ઇમ્પોર્ટ થયું.')}catch{setMessage(l==='en'?'This backup file could not be read.':'આ બેકઅપ ફાઇલ વાંચી શકાઈ નહીં.')}};reader.readAsText(file)};
  return <div className="page tools-page"><div className="page-heading"><span className="eyebrow">{l==='en'?'NO ACCOUNT REQUIRED':'એકાઉન્ટ જરૂરી નથી'}</span><h1>{l==='en'?'Your progress stays with you':'તમારી પ્રગતિ તમારી સાથે રહે છે'}</h1><p>{l==='en'?'Everything is stored in this browser. Export a backup before changing phones, clearing browser data or reinstalling the app.':'બધું આ બ્રાઉઝરમાં સાચવાય છે. ફોન બદલતા, બ્રાઉઝર ડેટા સાફ કરતા અથવા એપ ફરી ઇન્સ્ટોલ કરતા પહેલાં બેકઅપ એક્સપોર્ટ કરો.'}</p></div>
    <div className="tools-grid"><section><Download/><h2>{l==='en'?'Export my data':'મારો ડેટા એક્સપોર્ટ કરો'}</h2><p>{l==='en'?'Downloads progress, notes, bookmarks, favourites and preferences as one JSON file.':'પ્રગતિ, નોંધો, બુકમાર્ક, મનપસંદ અને પસંદગીઓ એક JSON ફાઇલમાં ડાઉનલોડ કરે છે.'}</p><button className="primary-button" onClick={exportData}><Download/>{l==='en'?'Download backup':'બેકઅપ ડાઉનલોડ કરો'}</button></section>
      <section><Upload/><h2>{l==='en'?'Import a backup':'બેકઅપ ઇમ્પોર્ટ કરો'}</h2><p>{l==='en'?'Restores a backup created by this app. Existing local progress will be replaced.':'આ એપ દ્વારા બનાવેલ બેકઅપ પુનઃસ્થાપિત કરે છે. હાલની લોકલ પ્રગતિ બદલાઈ જશે.'}</p><input ref={input} hidden type="file" accept="application/json" onChange={e=>importData(e.target.files?.[0])}/><button className="secondary-button" onClick={()=>input.current?.click()}><Upload/>{l==='en'?'Choose backup file':'બેકઅપ ફાઇલ પસંદ કરો'}</button></section>
      <section className="settings-section"><Settings2/><h2>{l==='en'?'Reading and audio':'વાંચન અને ઓડિયો'}</h2><label>{l==='en'?'Text size':'લખાણનું કદ'}<input type="range" min=".9" max="1.25" step=".05" value={state.fontScale} onChange={e=>setFontScale(Number(e.target.value))}/><span>{Math.round(state.fontScale*100)}%</span></label><label>{l==='en'?'Speech speed':'બોલવાની ગતિ'}<input type="range" min=".7" max="1.3" step=".1" value={state.audioRate} onChange={e=>setAudioRate(Number(e.target.value))}/><span>{state.audioRate.toFixed(1)}×</span></label></section>
      <section className="danger-section"><RotateCcw/><h2>{l==='en'?'Reset local data':'લોકલ ડેટા રીસેટ કરો'}</h2><p>{l==='en'?'Clears progress, notes and favourites from this browser. Export first if needed.':'આ બ્રાઉઝરમાંથી પ્રગતિ, નોંધો અને મનપસંદ સાફ કરે છે. જરૂર હોય તો પહેલાં એક્સપોર્ટ કરો.'}</p><button className="danger-button" onClick={()=>{if(confirm(l==='en'?'Reset all local data?':'બધો લોકલ ડેટા રીસેટ કરવો છે?'))reset()}}><RotateCcw/>{l==='en'?'Reset everything':'બધું રીસેટ કરો'}</button></section></div>
    {message&&<div className="toast-message">{message}</div>}
  </div>
}
